### ISSUE TITLE
most cited articles for a journal (venue)

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#10]
Use this query:

    SELECT ?work ?work_label (COUNT(?citing_work) AS ?count) WHERE {
      ?work wdt:P1433 wd:Q6294930.
      ?citing_work wdt:P2860 ?work.
      ?work rdfs:label ?work_label.
      FILTER((LANG(?work_label)) = "en")
    }
    GROUP BY ?work ?work_label
    ORDER BY DESC(?count)
    LIMIT 20

Using the Journal of Cheminformatics (wd:Q6294930) as an example.

**Comment by fnielsen** [comment]
In production. Example: https://tools.wmflabs.org/scholia/venue/Q6294930#Most%20cited%20articles
