### ISSUE TITLE
"Recently published sponsored work" in sponsor aspect should be ordered

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#1009]
"Recently published sponsored work" in sponsor aspect should be ordered. There is an "ORDER BY DESC(?publication_date) missing, see, e.g., https://tools.wmflabs.org/scholia/sponsor/Q11959645

**Comment by Daniel-Mietchen** [comment]
Not sure what you mean - this example actually looks correctly ordered to me, and Line 21 of [that query](https://query.wikidata.org/#%0ASELECT%20%3Fpublication_date%20%3Fnumber_of_citations%20%3Fwork%20%3FworkLabel%20%3Fquote%0AWITH%20%7B%0A%20%20SELECT%20%28MIN%28%3Fdate%29%20AS%20%3Fpublication_date%29%20%28COUNT%28%3Fciting_work%29%20as%20%3Fnumber_of_citations%29%20%3Fwork%20%28SAMPLE%28%3Fquote_%29%20AS%20%3Fquote%29%0A%20%20WHERE%20%7B%0A%20%20%20%20%3Fwork%20p%3AP859%2B%20%3Fsponsor_statement%20.%0A%20%20%20%20%3Fsponsor_statement%20ps%3AP859%2B%20wd%3AQ11959645%20.%0A%20%20%20%20OPTIONAL%20%7B%20%3Fsponsor_statement%20prov%3AwasDerivedFrom%2Fpr%3AP1683%20%3Fquote_%20.%20%7D%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%3Fwork%20wdt%3AP577%20%3Fdatetime%20.%0A%20%20%20%20%20%20BIND%28xsd%3Adate%28%3Fdatetime%29%20AS%20%3Fdate%29%0A%20%20%20%20%7D%0A%20%20%20%20OPTIONAL%20%7B%20%3Fciting_work%20wdt%3AP2860%20%3Fwork%20%7D%0A%20%20%7D%20%0A%20%20GROUP%20BY%20%3Fwork%0A%7D%20AS%20%25result%0AWHERE%20%7B%0A%20%20INCLUDE%20%25result%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cda%2Cde%2Ces%2Cfr%2Cjp%2Cnl%2Cno%2Cru%2Csv%2Czh%22%20%7D%0A%7D%20%0AORDER%20BY%20DESC%28%3Fpublication_date%29%20DESC%28%3Fnumber_of_citations%29%0ALIMIT%201000%0A) has 

```
ORDER BY DESC(?publication_date) DESC(?number_of_citations)
```

as expected.

**Comment by fnielsen** [comment]
I must not have my eyes open.
