### ISSUE TITLE
standardize file name for /missing/ for aspects

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1019]
At this moment individual/item pages under a topic can have a missing page (e.g. `/chemical/Q123/missing`), but we have a patch for `/chemical/` that does this for a full aspect. A comment by Finn in https://github.com/fnielsen/scholia/pull/883 wonders if we should have a systemized name for that file and suggests `${aspect}_empty_missing.html`.

Everyone okay? Then we implement this expectation.

**Comment by Daniel-Mietchen** [comment]
Makes sense to me.

**Comment by Daniel-Mietchen** [comment]
As per #1126, I think we should replace "missing" in page names with "curation" and thus go for `${aspect}_empty_curation.html`

**Comment by Daniel-Mietchen** [comment]
@egonw can you check whether what you had in mind here is covered by the pull request at https://github.com/fnielsen/scholia/pull/1324 ?

**Comment by egonw** [comment]
Agreed this should now follow `_curation`
