### ISSUE TITLE
add Twitter handle and hashtag to base.html

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1045]

**Comment by egonw** [comment]
See https://github.com/fnielsen/scholia/pull/1047

**Comment by fnielsen** [comment]
Do we have an example event with a Twitter handle and a Twitter hashtag?

**Comment by egonw** [comment]
- https://tools.wmflabs.org/scholia/event-series/Q77165314
- https://tools.wmflabs.org/scholia/event/Q77165107

**Comment by fnielsen** [comment]
And https://tools.wmflabs.org/scholia/event/Q64682140
