### ISSUE TITLE
engage with ScienceFinder 

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1065]
About their just launched tool: https://sciencefinder.techleap.nl/

**Comment by fnielsen** [comment]
Yes, interesting.

It is difficult to discover where any URI that correspond to, e.g., "Egon Willighagen" or "Maastricht University"

**Comment by egonw** [comment]
We've had our first email contact.

**Comment by egonw** [comment]
Late March we had a further follow up, and they will get back to me when they need input on Wikidata SPARQL tips to make them not time out.

**Comment by egonw** [comment]
I will dig up the email thread next week when I'm allowed to open my UM email again.

**Comment by egonw** [comment]
Not getting replies. We'll reopen when it becomes relevant again/
