### ISSUE TITLE
more prolific authors in some venue

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#11]
Again with JCheminf as example:

    SELECT ?author ?author_label (count(?work) as ?count) WHERE {
      ?work wdt:P50 ?author ;
            wdt:P1433 wd:Q6294930.
      ?author rdfs:label ?author_label . filter (lang(?author_label) = 'en')
    } group by ?author ?author_label
    order by desc(?count)
    limit 20

**Comment by fnielsen** [comment]
I am considering this:
```
#defaultView:ImageGrid
select (sample(?image) as ?animage) ?authorLabel (count(?work) as ?count) where {
  ?work wdt:P1433 wd:Q6294930 .
  ?work wdt:P50 ?author .
  optional { ?author wdt:P18 ?image_ . }
  bind(coalesce(?image_, <http://commons.wikimedia.org/wiki/Special:FilePath/1D_line.svg>) AS ?image)
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da" . } 
} group by ?author ?authorLabel
order by desc(?count)
limit 50
```
... but perhaps not so good.

**Comment by fnielsen** [comment]
In production. Example: https://tools.wmflabs.org/scholia/venue/Q6294930#Prolific%20authors
