### ISSUE TITLE
On topic profiles, add country-level citation network

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1101]
Ideally, the entries in the graph would link directly to the country/ topic profiles, e.g. as per
https://tools.wmflabs.org/scholia/country/Q668/topic/Q10737 .

**Comment by Daniel-Mietchen** [comment]
[Here](https://commons.wikimedia.org/wiki/File:Country-level_citation_graph_for_Zika_virus_publications,_as_per_Wikidata_Query_Service_on_6_April_2020.png) is a draft query for such a country-level citation network, using Zika virus as an example:

[![Country-level_citation_graph_for_Zika_virus_publications](https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Country-level_citation_graph_for_Zika_virus_publications%2C_as_per_Wikidata_Query_Service_on_6_April_2020.png/686px-Country-level_citation_graph_for_Zika_virus_publications%2C_as_per_Wikidata_Query_Service_on_6_April_2020.png)](https://commons.wikimedia.org/wiki/File:Country-level_citation_graph_for_Zika_virus_publications,_as_per_Wikidata_Query_Service_on_6_April_2020.png)

**Comment by Daniel-Mietchen** [comment]
On that basis, I played around with a suitable number of connections, and 30 to 50 seems to be useful for most cases.

**Comment by egonw** [comment]
What happens for multi-country articles that cite another multi-country article? I can imagine these graphs to very quickly become a network blob.

**Comment by Daniel-Mietchen** [comment]
@egonw In the query used in the PR at #1102 , there is a limit of the number of connections displayed, which I arbitrarily set to 42 after playing around with values between about 10 and about 100 for well-curated topics.

**Comment by fnielsen** [comment]
This is an interesting graph. It must be expensive if there are many papers. Wikipedia and Machine learning and biophysics worked fast though.

**Comment by fnielsen** [comment]
It is now running, e.g., at https://tools.wmflabs.org/scholia/topic/Q9035
