### ISSUE TITLE
Editorial delay support for Scholia

### ISSUE THREAD

**Issue by csisc** [fnielsen/scholia#1104]
I found that Wikidata lacks support of editorial dates for single research publications. Editorial delay are among the most important metrics for journals. That is why I propose to upload significant editorial dates (Received in, Revised in, and Published in) for research publications to Wikidata.

**Comment by Daniel-Mietchen** [comment]
The situation here is similar to #1105, on which I just commented that it is not up for Scholia to decide whether such data should be in Wikidata. So I suggest you bring up this matter on the WikiCite mailing list as well or on https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Source_MetaData , preferably in separate threads from your other suggestions, so these discussions can stay focused.

**Comment by csisc** [comment]
Moved to https://github.com/wikicite/wikicite-data.
