### ISSUE TITLE
Email support for authors

### ISSUE THREAD

**Issue by csisc** [fnielsen/scholia#1105]
I found that email support for scientists in Wikidata is limited. I propose to retrieve emails from research publications and upload these emails to Wikidata.

**Comment by Daniel-Mietchen** [comment]
Thanks for the suggestions, but that is not something Scholia can or should do on its own, so please bring it up in other channels. I just [responded](https://groups.google.com/a/wikimedia.org/d/msg/wikicite-discuss/Gj6Zcsu0ZzE/_EHfmBK1AgAJ) to your message to the WikiCite list and think that would be a good starting point for having this discussion.

**Comment by csisc** [comment]
Moved to https://github.com/wikicite/wikicite-data.
