### ISSUE TITLE
/scholia/doi/ fails with 500 on some DOIs

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#111]
Like https://tools.wmflabs.org/scholia/doi/10.1016/j.stem.2016.02.016 gives an "Internal Server Error"... 

The paper is in Wikidata: https://tools.wmflabs.org/scholia/work/Q23008981

It seems you need to upper case the DOI at some point... if I do that manually, it works...

**Comment by egonw** [comment]
See also https://github.com/fnielsen/scholia/issues/47

**Comment by fnielsen** [comment]
It is in production now.

**Comment by fnielsen** [comment]
See also #87
