### ISSUE TITLE
Handle new domain scholia.toolforge.org

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#1110]
There is a new domain name: See https://lists.wikimedia.org/pipermail/cloud-announce/2020-April/000275.html

We need to check what that means, if we need to change.

**Comment by Daniel-Mietchen** [comment]
I think we're done with this, but putting it on the list for today just to make sure.

**Comment by egonw** [comment]
There is some old domain names left on GitHub, but I think we got most of it, indeed. See https://github.com/search?q=%22tools.wmflabs.org%2Fscholia%22+-user%3Anunogit&type=code

**Comment by Daniel-Mietchen** [comment]
When resorting this list by date, a few places pop up where it would make sense to make the change: https://github.com/search?o=desc&q=%22tools.wmflabs.org%2Fscholia%22+-user%3Anunogit&s=indexed&type=Code .

**Comment by Daniel-Mietchen** [comment]
I left a few pull requests in repos that had recently used the old URL pattern and think this can be closed now.
