### ISSUE TITLE
Rename "missing" pages into "curation" pages

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1126]
- to clarify their purpose
- leaving redirects

**Comment by egonw** [comment]
@Daniel-Mietchen, is this a proposal, or already approved and the patch just needs writing?

**Comment by Daniel-Mietchen** [comment]
At this point, it is just a proposal &mdash; we have not discussed this yet. I hope to get some feedback on this today.

**Comment by egonw** [comment]
I like the idea.

**Comment by Daniel-Mietchen** [comment]
My motivation here is that "/missing" is a bit too ambiguous. When demoing the site to new users, phrases like "the missing pages for organizations" are then potentially misleading.

Calling them "curation" would make their purpose clearer.

**Comment by Daniel-Mietchen** [comment]
This has several components that need to be coordinated:
1) rename the missing pages
2) rename references to the missing pages
3) add redirects from /missing to /curation
4) perhaps think about some consistent formatting, such that the curation links on the profile pages show up in a predictable way/ place

**Comment by Daniel-Mietchen** [comment]
As just discussed, we are going to treat this ticket as being about 1-3, opening a new one for 4, which is #1322.

**Comment by Daniel-Mietchen** [comment]
As just discussed, I will work on 1 and 2, and once that is set up, @egonw will do 3.

**Comment by Daniel-Mietchen** [comment]
@egonw I think I am through with the renaming &mdash; see https://github.com/fnielsen/scholia/tree/origin/feat/curation-pages-1126 for current state.

**Comment by Daniel-Mietchen** [comment]
Just for the record, we now have a pull request for this at https://github.com/fnielsen/scholia/pull/1324 .

**Comment by carlinmack** [comment]
Sorry to nitpick, but is it on purpose that the URL is only available without the final /?

For example https://scholia.toolforge.org/topic/Q202864/curation vs https://scholia.toolforge.org/topic/Q202864/curation/

**Comment by carlinmack** [comment]
It seems that this is the behaviour on most pages (like any with a Q number). This seems to be a bigger than this so will create a separate issue
