### ISSUE TITLE
update the URL on the GitHub profile

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1145]
It currently points to the Toolforge URL pattern that is being phased out:

![image](https://user-images.githubusercontent.com/26721/83414372-ab1c8000-a41d-11ea-9821-37fb4f624c08.png)

**Comment by Daniel-Mietchen** [comment]
The new URL pattern is https://scholia.toolforge.org/ .

**Comment by fnielsen** [comment]
I have updated it. I guess there are a lot of other places.

**Comment by egonw** [comment]
Yes, I guess so too. Let's update them when we see them. This one I could not fix, as far as I could see.

**Comment by Daniel-Mietchen** [comment]
Here is a list: https://github.com/fnielsen/scholia/search?q=wmflabs . Also includes links to other Toolforge tools, e.g. Author Disambiguator and QuickStatements.
