### ISSUE TITLE
canonical URLs and/or rewrites?

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1151]
With the toolforge URL change upcoming, we need to get people to use the new site. There are already some fixes here: https://github.com/fnielsen/scholia/pull/1149

But we need more, I think. Thoughts please.

**Comment by Daniel-Mietchen** [comment]
Probably makes sense to put such things into a config file rather than hardcoding it.

**Comment by egonw** [comment]
Yeah, I think @nunogit is working on that, but let's not have that block this fix.

**Comment by Daniel-Mietchen** [comment]
There is https://github.com/fnielsen/scholia/pull/1037 for the config file.

**Comment by egonw** [comment]
This issue is also about having the canonical URL in the `<html><head>`.
