### ISSUE TITLE
Give all sections on all Scholia pages suitable section IDs

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1157]
e.g. in author profiles like https://tools.wmflabs.org/scholia/author/Q4693015 , sections like the most recent publications do not currently have such an ID.

**Comment by egonw** [comment]
I would be nice to have a "menu" on the left side as kind of a table of contents.

**Comment by egonw** [comment]
An example of `<h>` element with identifier is given below for `venues.html`:

```xml
<h2 id="Citations to work ratio">Citations to work ratio</h2>
```

This allows linking to it to with URLs like: https://scholia.toolforge.org/venues/Q15755805,Q15757650#Citations%20to%20work%20ratio

But many header elements do not yet.

**Comment by egonw** [comment]
Outdated: section IDs have now a detailed format, to accommodate the external SPARQL.
