### ISSUE TITLE
Bibtex generation fails for \cite{Q123,Q234.Q345}

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#116]
Bibtex generation fails for \cite{Q123,Q234.Q345}. If the Qs are wrongly formatted then the script fails completely.

**Comment by larsgw** [comment]
What do you expect the correct output to be?

  - `['Q123']`, i.e. split by comma and filter out everything that is not a correct QID, or
  - `['Q123', 'Q234', 'Q345']`, i.e. find every substring matching `Q\d+` (which could be extended with `\b` to avoid `NielsenSPARQ2019` matching)
