### ISSUE TITLE
create `brain region` aspect

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1162]
As requested in https://github.com/fnielsen/scholia/issues/136.

```sparql
SELECT ?region ?regionLabel WHERE {
  ?region wdt:P31 wd:Q1620186 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```

**Comment by egonw** [comment]
@fnielsen, what kind of information do you like to be given on this aspect? `has part` and 'part of' sound reasonable, but what more did you have in mind?

**Comment by fnielsen** [comment]
Hmmm... I do not know. The work I did some time ago used specialized visualizations. It is not clear to me how much extra we can put in compared to "topic".

**Comment by fnielsen** [comment]
When looking at Putamen, for instance, https://www.wikidata.org/wiki/Q550934, I do not see we can put in that much extra information.

**Comment by egonw** [comment]
Shall we close the issue then?

**Comment by fnielsen** [comment]
I suppose it was more a wish or and attempt for a hopeful inspiration than a concrete idea.
