### ISSUE TITLE
Update the Scholia page view statistics notebook

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#1166]
https://github.com/fnielsen/scholia/blob/master/notebooks/pageview-statistics.ipynb

New URL for the toolviews tool: https://toolviews.toolforge.org/api/v1/tool/scholia/daily/2018-04-30/2020-06-21

**Comment by ivanhercaz** [comment]
This seems an easy task in which I could help you if you want stop worrying about it. I understand I just have to executed the notebook and upload it with the updated results, then propose a PR and wait for your review.

If you are agree, just confirm me.

**Comment by fnielsen** [comment]
This seems to have been fixed with 39eee82edc327505f0af5969cd19e7a836c1d78f
