### ISSUE TITLE
"published in" data in the header of the works

### ISSUE THREAD

**Issue by ivanhercaz** [fnielsen/scholia#1167]
There are some kind of publications, like the scholarly articles, the chapters and the conference papers that are linked to the "main work" in which them are published: a scholarly article in a journal, a conference paper in a specific proceedings, etc.

I have been thinking about it in the past few days while I have been working in the project Wikidata-IATEXT. I think it would be very useful if Scholia shows in the header of the "work" pages this data, I mean the one set with [P1433](https://www.wikidata.org/wiki/Property:P1433) ("published in"). A good location may be where Scholia shows the identifiers of the article, like the DOI (I attached below two screenshots with a rectangle of the zone I am referring).

I admit you that I don't know if you already open an issue to discuss it or if you have closed some issue in which this idea was rejected. There are a lot of issues and now I can not check them, excuse me for the possible duplication.

Regards

![scholia_published_01](https://user-images.githubusercontent.com/8690921/86135082-4454ba00-bae2-11ea-89f7-575e5031eced.png)
![scholia_published_02](https://user-images.githubusercontent.com/8690921/86135077-43238d00-bae2-11ea-95f6-dae798e36549.png)

**Comment by fnielsen** [comment]
Now running. Example: https://scholia.toolforge.org/work/Q21090025

**Comment by ivanhercaz** [comment]
Crear work, @fnielsen ! Thank you very much for the implementation of this feature.
