### ISSUE TITLE
Clean commented iframes from html code.

### ISSUE THREAD

**Issue by nunogit** [fnielsen/scholia#1169]
Clean commented iframes. This creates noise in iframe testing:

https://scholia.toolforge.org/author/Q18618629
 
`
--
<div id="topics-works-matrix"></div>
  |  
  | 
  |  
`

**Comment by fnielsen** [comment]
I am not sure I understand the problem.

**Comment by fnielsen** [comment]
I suppose the "" can be erased.

**Comment by scholiagit** [comment]
Not really sure what happened, but this ticket was create twice.

Please look at #1170

Even the title in #1170 doesn't look as expected.
