### ISSUE TITLE
also list `author name strings` in tables

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1177]
![image](https://user-images.githubusercontent.com/26721/87564734-0bf7d300-c6c1-11ea-9de1-8e6fb1a89872.png)

And update the string below this to not refer to missing authors, but refer to unlinked author.

**Comment by egonw** [comment]
@fnielsen, @Daniel-Mietchen, what do you think of this?

Alternatively, we push for the suggestion that @larsgw made: replace all "author name string" with 'author" with an unknown value and a 'states as' qualifier, and removing "author name string" as property.

**Comment by larsgw** [comment]
See this tweet: https://twitter.com/larswillighagen/status/1286364870447968259

**Comment by fnielsen** [comment]
This seems to be the same as #549  and implemented as 58c8575790be55d257b0b2306a93fc5fd58128aa

**Comment by fnielsen** [comment]
https://scholia.toolforge.org/work/Q57588977

**Comment by egonw** [comment]
Awesome!
