### ISSUE TITLE
register Scholia with identifiers.org?

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1184]
Identifiers.org is a identifier resolver and registry (aimed at the life sciences) and has several registries entries for which we have redirectors, e.g. for DOI: https://registry.identifiers.org/registry/doi

What about registering our redirect features with identifiers.org?

**Comment by Daniel-Mietchen** [comment]
Sounds like a good idea to explore that. Not sure what their policies are on completeness, though, since our redirects are filtered by existence of an appropriate record in Wikidata, which is not necessarily the case for the services they have already indexed.

**Comment by egonw** [comment]
@nsjuty, can you say something about the completeness @Daniel-Mietchen asks about?

**Comment by egonw** [comment]
Completeness is not a blocker, we learned.

**Comment by Daniel-Mietchen** [comment]
Sounds good, so I'd say let's give it a try!

**Comment by egonw** [comment]
Okay, the forms are really confusing and do not really allow resources to be hosted by more than on institute, but I just proposed Scholia as resource for the WikiPathways identifier. If that worked, I'll proceed with others.

**Comment by egonw** [comment]
Remote issue has been reopened and a new discussion has been started on the completeness requirement.

**Comment by egonw** [comment]
They ended up approving our first round suggestions, with the note "based on either the existence of a primary provider, or promotion of an existing one". Let's leave it at that at this moment, to not reboot their internal discussions.
