### ISSUE TITLE
organize an October "general assembly" 

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1186]
A full day meeting, with all participants there, but at the very least one PI from each partner (Finn, Daniel/Lane, Egon), with status reports on all 8 proposal projects, and a planning session for how to finish the work for this grant.

@ammar257ammar, can you plz set up a Doodle to find a day in October to have such a project meeting to plan the final half year of this grant? cc @fnielsen @Daniel-Mietchen @bluerasberry

**Comment by ammar257ammar** [comment]
The Doodle is created and this is the URL (I will spread it through email too)

https://doodle.com/poll/queubdyi7tergpq2
