### ISSUE TITLE
maybe max(?birthdate)?

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#12]
The SPARQLs for the "venue" list the birthdates of workers, and uses:

    (min(?birthdates) as ?birthdate)

But if multiple dates are given for someone, like one with only a year, the date is defaulted to the January 1, the minimum... it seems to me that "min(?birthdates)" returns the least precise information?

**Comment by fnielsen** [comment]
I suppose you mean the "organization" list?

**Comment by egonw** [comment]
Thanks!
