### ISSUE TITLE
Look into integration with Fatameh

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#120]
Fatameh is a new webservice. Is this useful for Scholia or just the same as Magnus Manske do? http://tools.wmflabs.org/fatameh

**Comment by Daniel-Mietchen** [comment]
It can take a PMID or PMCID and create/ update the corresponding bibliographic item:
- https://tools.wmflabs.org/fatameh/pmc/add/PMC6310123
- https://tools.wmflabs.org/fatameh/pmid/add/31180813 .

SourceMD is not always available, so it is useful to have an alternative.

**Comment by Daniel-Mietchen** [comment]
Fatameh is not around any more, so closing this.
