### ISSUE TITLE
Prepare the Scholia hackathon on November 5, 2020

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1204]
currently planned for the European morning of Oct 29.

**Comment by Bam92** [comment]
We are planning to do a hackathon at the end of the month and we would be pleased to discuss Scholia. Do you have any suggestions?

**Comment by Daniel-Mietchen** [comment]
Hi @Bam92 do you have any more information about your event? In general, good issues to start with would be those with the [good first issue](https://github.com/fnielsen/scholia/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aopen) label.

The hackathon that this ticket refers to is more or less an internal one by the Scholia development team.

**Comment by Daniel-Mietchen** [comment]
We now have a dedicated milestone for this: https://github.com/fnielsen/scholia/milestone/5
