### ISSUE TITLE
Update all links to the Author Disambiguator

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1242]
We are currently linking to the Author Disambiguator via links to pages like
https://author-disambiguator.toolforge.org/?doit=Look+for+author&name=Yang%20Yang
that go to publicly visible pages that are rate-limited.

The Author Disambiguator also has pages like
https://author-disambiguator.toolforge.org/names_oauth.php?doit=Look+for+author&name=Yang%20Yang
that are not publicly visible, require OAuth authentication and are not rate limited.

We should probably link to the latter, since these outgoing links are meant for curation, which would involve editing and thus authentication.

**Comment by egonw** [comment]
I'm on it.
