### ISSUE TITLE
Convert chem* aspects into external SPARQL query format

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1270]
as per https://github.com/fnielsen/scholia/pull/1267

- [x] chemical
- [x] chemical-class
- [x] chemical-element

**Comment by egonw** [comment]
https://github.com/fnielsen/scholia/pull/1291

**Comment by egonw** [comment]
Patch for `chemical-class`: https://github.com/fnielsen/scholia/pull/1305

**Comment by egonw** [comment]
Patch for `chemical-element`: https://github.com/fnielsen/scholia/pull/1306

**Comment by egonw** [comment]
All branches have been merged.
