### ISSUE TITLE
Uncaught ReferenceError: set is not defined 

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#1310]
I get "Uncaught ReferenceError: set is not defined" at:  
` if (item.claims.P31[0].mainsnak.datavalue.value.id in set(['Q47461491', 'Q967847'])) {` for https://scholia.toolforge.org/event/Q50355797

This relates to a new commit by @egonw

**Comment by egonw** [comment]
It seems I am using a Python `set()` command that is not defined in all implementations.

**Comment by egonw** [comment]
Sorry for not seeing this. Fix available as PR.
