### ISSUE TITLE
Specialized aspects

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#136]
Specialized aspects for neuroinformatics, bioinformatives.

Neuroinformatics 
- [x] Brain regions

Bioinformatics
- [x] Protein
- [x] Disease
- [x] Genes
- [x] Pathway

Cheminformatics
- [x] Chemical

**Comment by fnielsen** [comment]
Genes were added with #205

**Comment by fnielsen** [comment]
Pathways were added with #174

**Comment by egonw** [comment]
Decision on 'brain region' has been reached too.
