### ISSUE TITLE
Update tox.ini with py37 

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#1405]
Update tox.ini with py37 as Python3.7 is used on Toolforge

**Comment by ivy-2000** [comment]
```
[testenv:py37]
commands = 
    python -m pytest --doctest-modules scholia
    python -m pytest tests
deps=
    pytest
    -rrequirements.txt
```
I think this should be added as well to tox.ini. I'm not entirely familiar with the code base and was wondering if any other chances need to be done to the dependencies and commands, before opening a pr. 
@fnielsen

**Comment by fnielsen** [comment]
> I think this should be added as well to tox.ini.

Yeps, I seem to have forgotten that.

**Comment by fnielsen** [comment]
Thanks for the comment! It should be fixed now.
