### ISSUE TITLE
Add gender distribution for award recipients (award aspect)

### ISSUE THREAD

**Issue by dartar** [fnielsen/scholia#141]
What the title says, it would be great to surface gender skew across awards, something not many other sources can provide.

**Comment by fnielsen** [comment]
Implement with 5dc3d344e84181290bcef81866500d2f1589a05e and in production with, e.g., https://tools.wmflabs.org/scholia/award/Q18357422#Gender%20distribution

**Comment by dartar** [comment]
Brilliant, thanks so much, how about adding some of the top prizes by popularity/# of laureates in the examples section? This sounds like an excellent way to showcase the power of Scholia and Wikidata.

**Comment by fnielsen** [comment]
I wonder how one would identity the "top prizes"?
