### ISSUE TITLE
opt-out of FLoC

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#1419]
See https://plausible.io/blog/google-floc

![image](https://user-images.githubusercontent.com/26721/115112751-4ad7f380-9f87-11eb-9ea4-e5c56fc42321.png)

**Comment by Daniel-Mietchen** [comment]
Yes, opting out is the sensible thing to do. I think we do not have access to the `.htaccess` file, but the Permissions-Policy header (which is new to me) seems doable.

**Comment by supertassu** [comment]
The Toolforge web proxy already does this for all tools.

**Comment by egonw** [comment]
> The Toolforge web proxy already does this for all tools.

@supertassu, is there a page we can link to with info about this decision and why it matters, that we can then link to from the Scholia page?

**Comment by supertassu** [comment]
Yes, https://phabricator.wikimedia.org/T279804

**Comment by Daniel-Mietchen** [comment]
Looks like we're all good here. Closing.
