### ISSUE TITLE
Prepare participation in Wikimedia Hackathon on May 22-23, 2021

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1429]
as per https://www.mediawiki.org/wiki/Wikimedia_Hackathon_2021

**Comment by Daniel-Mietchen** [comment]
I set up a [ticket](https://phabricator.wikimedia.org/T282395) for Scholia activities during the hackathon.

**Comment by Daniel-Mietchen** [comment]
We now also have a [dedicated milestone](https://github.com/fnielsen/scholia/milestone/14) for the hackathon.

**Comment by egonw** [comment]
> We now also have a [dedicated milestone](https://github.com/fnielsen/scholia/milestone/14) for the hackathon.

I added https://github.com/fnielsen/scholia/issues/1431
