### ISSUE TITLE
In topic aspect, most recent papers are often actually not the most recent ones

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#148]
e.g. in 
https://tools.wmflabs.org/scholia/topic/Q202864
that's because the  
```SPARQL
LIMIT 500 
```
comes with the first subquery rather than later one.
I presume that is for performance reasons, and if that is the case, suggest to go for a limit of 100 or 50 instead, but right at the end, i.e. after the date filtering.

**Comment by fnielsen** [comment]
https://tools.wmflabs.org/scholia/topic/Q202864 works now
