### ISSUE TITLE
Link external IDs

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#151]
Link external IDs, e.g., on https://tools.wmflabs.org/scholia/chemical/Q47512

**Comment by egonw** [comment]
The proper URL can be created with this updated query:


    SELECT ?IDpred ?IDpredLabel ?id ?formatterurl ?idurl WHERE {  
      wd:Q423248 ?IDdir ?id .
      ?IDpred wikibase:directClaim ?IDdir ;
              wdt:P31 wd:Q19833835 .
      OPTIONAL { 
        ?IDpred wdt:P1630 ?formatterurl .
      }
      BIND(IRI(REPLACE(?formatterurl, '\\$1', str(?id))) AS ?idurl).
      SERVICE wikibase:label { bd:serviceParam wikibase:language "en,da,de,es,fr,jp,nl,no,ru,sv,zh" . }
    }
    ORDER BY ASC(?IDpredLabel)
    LIMIT 500

**Comment by egonw** [comment]
@fnielsen, can you give me a pointer here? The above SPARQL creates the URL, but how to I get Scholia to use a "url" column for the link behind the ?id value?

Basically all tables recognize Wikidata entries, and use that to create a link, and for the ORCID there is some magic based on the column name... I am looking for an existing example that combines the content of two columns into one column, pretty much like ?foo and ?fooLabel...

Does a combination something like ?foo and ?fooURL already exist? If so, got a pointer? If not, would that be the approach we would like to implement?

**Comment by fnielsen** [comment]
I think we need to implement some more.

**Comment by fnielsen** [comment]
I am wondering if it is possible for an adverserial to change Wikidata items to do a cross domain attack.

**Comment by egonw** [comment]
Yes, I think it would... but that is not specific to Scholia, but to Wikidata in general... We can only hope the spam/vandalism bots do their work properly...

**Comment by fnielsen** [comment]
Now running, e.g., here https://tools.wmflabs.org/scholia/chemical/Q2270
