### ISSUE TITLE
Figure out why scholia/Q935387 is opened as topic and not as chemical

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#165]
(to be assigned to me)

Check why https://tools.wmflabs.org/scholia/Q935387 does not point to https://tools.wmflabs.org/scholia/chemical/Q935387 but to /topic/

**Comment by fnielsen** [comment]
These "class" mappings are currently hardcoded in `q_to_class` in `query.py`. I've been thinking of moving the setup to a file. Another solution would be some form of more intelligent way, e.g., machine learning.

**Comment by egonw** [comment]
Oh! None of the chemicals are working... ah, that never got implemented yet! OK... patch coming :)

**Comment by fnielsen** [comment]
In production https://tools.wmflabs.org/scholia/Q47512
