### ISSUE TITLE
what if Scholia had RSS feeds?

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#171]
For example, for a work a feed with new citing articles, for a journal and topics new articles, etc?

**Comment by egonw** [comment]
(Or an atom feed...)

**Comment by egonw** [comment]
Actually... I'm lacking some knowledge here, so not a Sat morning hack :( @fnielsen, so, I first need to know how I can use flask (?) to create non-HTML pages...  

I found this: http://flask.pocoo.org/snippets/10/ but lack to much flask knowledge to see how this could fit it... @fnielsen, is there code in Scholia right now that is not HTML and uses Python to dynamically create content?

**Comment by egonw** [comment]
Is this something that can be set up with views.py? That is, I can make an alternative "renderer", right? That does not use a HTML template, but an RSS template? Correct?

**Comment by fnielsen** [comment]
You just return the object for non-HTML and then one needs to change the mimetype. For json there are standard functions: https://github.com/fnielsen/wembedder/blob/master/wembedder/app/views.py. I do not know about feeds, though.

**Comment by egonw** [comment]
Super, I now see the /api/ section! Exactly what I needed... (well, now I need to find time again... not before the end of this month...)

**Comment by egonw** [comment]
OK, I found enough time to play with it a bit 

https://github.com/egonw/scholia/tree/feature/rss

*But*, it's far from finished... I will send a PR when it's ready...

**Comment by egonw** [comment]
OK, I also figured out how to the the SPARQL now and return the items in the channel:

![image](https://user-images.githubusercontent.com/26721/31585168-8acdbeea-b1bd-11e7-9d62-71ce2d6aca14.png)

@fnielsen, feedback welcome! If you like this, I can start working on doing similar feeds for latest-articles-about-a-topic, latest-citations-to-an-article, etc...

**Comment by egonw** [comment]
The current idea is to have the feed URLs as extensions of the aspect URLs:

- /author/{q}/latest/rss

The first part mirrors the matching aspect, while the third "/latest/" refers basically to the matching query... the "/rss" refers to the format, allowing for "/atom" or "/json" later, if needed...

**Comment by egonw** [comment]
OK, this draft would be nice to have online, so that I can recruit people to test it: https://github.com/fnielsen/scholia/pull/217

**Comment by fnielsen** [comment]
Our first implementation is now running at: https://tools.wmflabs.org/scholia/author/Q20895241/latest-works/rss

**Comment by egonw** [comment]
Suggested GUI integration: https://github.com/fnielsen/scholia/pull/234

Once something like that is applied, I suggest to close this issue and get people to use it, adding additional feeds based on feature requests they post here.
