### ISSUE TITLE
Co-authors

### ISSUE THREAD

**Issue by magnusmanske** [fnielsen/scholia#2]
Too lazy for pull request; suggest using co-authors in sci articles AND books, using:
```
  VALUES ?type { wd:Q13442814 wd:Q571 } .
  ?work wdt:P31 ?type . 

```

**Comment by fnielsen** [comment]
Thanks for the lazy pull request. I put in books now. And I also added "scientific conference articles". I note that "MediaWiki" lists you are "author". In Danish, P178 sounds more appropriate for software. Perhaps it would be better to leave out a P31 restriction altogether.
