### ISSUE TITLE
open disease, chemical, etc as "topic"

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#201]
Right now, some topics end up on a special page, like gene, disease, etc... but the "topic" page template often has additional, complementary information (queries). That made me think to have links/buttons just below the title with something like "open as topic"...

This "issue" is to discuss this idea...

**Comment by egonw** [comment]
@fnielsen, would you be happy with just a link below the description (if available) saying "Open as topic"?

**Comment by fnielsen** [comment]
Yes. There are a number of aspects that have this issue. For instance, some organizations can be viewed both as "organization" and "sponsor", - and I suppose also as topic.

**Comment by egonw** [comment]
@fnielsen, you indicated this functionality was already implemented... so, can this issue be closed then?

**Comment by fnielsen** [comment]
Yeah. The styling could be improved though and further catching

**Comment by fnielsen** [comment]
Aspect-chooser: 4451de6725c9ff8295b0b4c0ae12d5a94fb02253
