### ISSUE TITLE
Select multiple topics

### ISSUE THREAD

**Issue by belett** [fnielsen/scholia#207]
Hi,

Some topics are quite large it could be useful to select and cross multiples topics, for instance:

https://tools.wmflabs.org/scholia/topic/Q42Q52 for publication about Douglas Adams and Wikipedia (dumb example but the point is that we will never have an item about "Douglas Adams and Wikipedia").

**Comment by fnielsen** [comment]
This is related to  Aspects for combinations of Qs #71

**Comment by belett** [comment]
Great, I've searched for a similar issue but didn't find it.
I was too specific, combination of topic and author and not just topics would be even better than what I suggested.

**Comment by fnielsen** [comment]
There is now an aspect for multiple topics. Example: https://tools.wmflabs.org/scholia/topics/Q52,Q2013 

There are only two panels. We can probably come up with more panels. Let me know if you want anything specific.
