### ISSUE TITLE
SPARQL query run on award page generates error

### ISSUE THREAD

**Issue by tarrow** [fnielsen/scholia#221]
The SPARQL query run on the awards page gets back a 503 from query.wikidata.org. This means the page doesn't show properly and is full of errors.

The attempted page is: `https://query.wikidata.org/sparql?query=%23defaultView%3AScatterChart%0A%23%20Statistics%20on%20number%20of%20recipients%20for%20award%20wrt.%20gender%0ASELECT%20%3Fmales%20%3Ffemales%20%3Faward%20%3FawardLabel%20%0AWITH%20%7B%0A%20%20SELECT%20(COUNT(%3Frecipient_male)%20AS%20%3Fmales)%20(COUNT(%3Frecipient_female)%20AS%20%3Ffemales)%20%3Faward%20WHERE%20%7B%0A%20%20%20%20%3Faward%20wdt%3AP31%20wd%3AQ11448906%20.%0A%20%20%20%20%7B%20%0A%20%20%20%20%20%20%3Frecipient_male%20wdt%3AP166%20%3Faward%20.%0A%20%20%20%20%20%20%3Frecipient_male%20wdt%3AP21%20wd%3AQ6581097%20.%0A%20%20%20%20%7D%0A%20%20%20%20UNION%20%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%3Frecipient_female%20wdt%3AP166%20%3Faward%20.%0A%20%20%20%20%20%20%3Frecipient_female%20wdt%3AP21%20wd%3AQ6581072%20.%0A%20%20%20%20%7D%20%20%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Faward%0A%7D%20AS%20%25result%0AWHERE%20%7B%0A%20%20INCLUDE%20%25result%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cen%2Cda%2Cde%2Ces%2Cfr%2Cjp%2Cnl%2Cno%2Cru%2Csv%2Czh%22.%20%7D%0A%7D%20%0AORDER%20BY%20DESC(%3Fmales)%20DESC(%3Ffemale)%20`

This also errors if you try to load it in a browser with the standard WMF error page.

I think the URL may be just too long. If you chop the query down by the inital comment then it works.

**Comment by fnielsen** [comment]
The scatterplot on this page https://tools.wmflabs.org/scholia/award/ works ok now. A couple of hours ago I saw an error message from Wikidata Query Service, so perhaps it is a transient error. I have not seen the error before.

**Comment by tarrow** [comment]
Yep, must be a transient error. Visiting that address in the browser now works fine. How odd...

I'll close though.
