### ISSUE TITLE
Publications per year graph sometimes not usable

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#224]
E.g. for agriculture:
https://tools.wmflabs.org/scholia/topic/Q11451

**Comment by fnielsen** [comment]
I see the sorting is bad.

**Comment by fnielsen** [comment]
There is a related Stackoverflow question: https://stackoverflow.com/questions/47562736/should-xsddate-convert-for-datetimes-before-common-era-in-sparql

**Comment by fnielsen** [comment]
Now running here: https://tools.wmflabs.org/scholia/topic/Q11451
