### ISSUE TITLE
Pages about publishers not easily findable

### ISSUE THREAD

**Issue by pigsonthewing** [fnielsen/scholia#246]
https://tools.wmflabs.org/scholia/Q905549 (for example) redirects to https://tools.wmflabs.org/scholia/topic/Q905549 - which is a topic page.

Perhaps for publishers the redirect should be to pages like https://tools.wmflabs.org/scholia/publisher/Q905549 ? Or at least the former page should have a prominent link to the latter.

**Comment by egonw** [comment]
I guess this is just about the RSC not being typed as publisher... (which I just added): https://www.wikidata.org/w/index.php?title=Q905549&type=revision&diff=624387306&oldid=622490939

**Comment by pigsonthewing** [comment]
Thank you; yes. My first link now redirects to https://tools.wmflabs.org/scholia/publisher/Q905549
