### ISSUE TITLE
Include tools used in research as stated with P4510

### ISSUE THREAD

**Issue by nichtich** [fnielsen/scholia#264]
See https://www.wikidata.org/wiki/Property:P4510: For instance we have [40 publications about Amazon Mechanical Turk](https://tools.wmflabs.org/scholia/topic/Q733115) but 381 publications that used it for their research. Another example is [Large Hadron Collider](https://www.wikidata.org/wiki/Q40605): many publications with research that used it but only a small number about it.

**Comment by fnielsen** [comment]
We have a use aspect:
* https://tools.wmflabs.org/scholia/use/Q733115
* https://tools.wmflabs.org/scholia/use/Q40605
This might not be that discoverable.
