### ISSUE TITLE
acetic acid is not recognized as chemical compound

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#275]
... but as general topic:

![image](https://user-images.githubusercontent.com/26721/37856316-346b6a70-2ef4-11e8-91d8-fe9057676fd0.png)

Reproduce by following this link: https://tools.wmflabs.org/scholia/Q47512

**Comment by Daniel-Mietchen** [comment]
Seems we'll have to parse the subclass hierarchy more deeply for cases like this.

**Comment by egonw** [comment]
OK, the problem is that the SPARQL only returns one class:

```sparql
select ?class where {{ wd:{q} wdt:P31 ?class }}
```

It only returns carboxylic acid, which is likely because it has the highest priority and only values of the highest priority are returned... this is an issue with much higher impact...
