### ISSUE TITLE
From every non-topic aspect, add a link to the corresponding topic aspect

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#282]
E.g. from
https://tools.wmflabs.org/scholia/taxon/Q202864
to
https://tools.wmflabs.org/scholia/topic/Q202864

**Comment by fnielsen** [comment]
Implmented with 4451de6725c9ff8295b0b4c0ae12d5a94fb02253

**Comment by Daniel-Mietchen** [comment]
@fnielsen this links from every aspect to the topic aspect, including from the topic aspect.
Example: https://tools.wmflabs.org/scholia/topic/Q52558626 .

**Comment by fnielsen** [comment]
It does not link from every aspect, e.g., not from you as author: https://tools.wmflabs.org/scholia/author/Q20895785 because noone is using you as a topic. It is correct that the topic aspect links to the topic. Maybe this should be fixed.
