### ISSUE TITLE
In work aspect, display more complete bibliographic metadata, not just the title

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#288]
i.e. 
https://tools.wmflabs.org/scholia/work/Q27932040
would display something like

```
Scherrer T, Mittal N, Janga SC, Gerber AP (2010) A Screen for RNA-Binding Proteins in Yeast Indicates Dual Functions for Many Enzymes. PLoS ONE 5(11): e15499. https://doi.org/10.1371/journal.pone.0015499
```

as generated based on the information stored in Wikidata, similar to how 
https://www.wikidata.org/wiki/Module:Cite
does that.

This idea comes from [here](https://github.com/Daniel-Mietchen/ideas/issues/344#issuecomment-377726319).

**Comment by fnielsen** [comment]
Implemented with 99b2743bf34651491472b2e616fb22ae72c8ba26
