### ISSUE TITLE
HTTP 500 error for /author/random

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#298]
as of now
https://tools.wmflabs.org/scholia/author/random .

Noticed in relation to #284 .

**Comment by fnielsen** [comment]
I get "Internal Server Error"

**Comment by fnielsen** [comment]
Neither works:
```
SELECT ?author WHERE {
  ?author ^wdt:P50 / wdt:P31 wd:Q13442814 .
}
ORDER BY RAND()
LIMIT 1
```

**Comment by fnielsen** [comment]
Two SPARQL queries after each other. 
```SPARQL
SELECT *
WITH {
  SELECT (COUNT(?author) AS ?count) WHERE {
    [] wdt:P50 ?author
  }
} AS %count
WHERE {
  INCLUDE %count
  [] wdt:P50 ?author
  BIND(xsd:integer(RAND() * ?count) AS ?random)
}
OFFSET 1508845
LIMIT 1
```

**Comment by Daniel-Mietchen** [comment]
Such "t1105721757" results usually indicate cases where a statement has things like "unknown".
I suppose this is a bug in the serialization - not sure whether there is a Phabricator ticket for this.
