### ISSUE TITLE
In taxon aspect, the graph should go both ways

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#334]
E.g. for Flavivirus, the Zika virus does not currently show up even though it has the parent taxon Flavivirus:
https://tools.wmflabs.org/scholia/taxon/Q1165479 

Another test case is mammals: https://tools.wmflabs.org/scholia/taxon/Q7377

**Comment by pigsonthewing** [comment]
> I suppose one could do a single step.

Maybe with some sort of indicator as to whether the child-taxa are terminal nodes or have children themselves?

**Comment by egonw** [comment]
One step, and perhaps putting a limit on it?

**Comment by fnielsen** [comment]
There is now a one step implementation with limits: https://tools.wmflabs.org/scholia/taxon/Q1165479
