### ISSUE TITLE
On Scholia landing page, provide some overview stats about Wikidata and scholarly publications in it

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#336]
e.g. [number of triples in Wikidata](https://query.wikidata.org/#SELECT%20%28count%28%2a%29%20as%20%3Fcounts%29%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo%20.%0A%20%20%7D)

```SPARQL
SELECT (count(*) as ?counts) WHERE {
  ?s ?p ?o .
  }
```
and some WikiCite-focused ones, e.g. as per [this list](https://www.wikidata.org/wiki/User:Research_Bot#Usage_stats_for_scientific_articles_and_some_related_identifiers)

or some version of http://wikicite.org/statistics.html .

**Comment by fnielsen** [comment]
Now running https://tools.wmflabs.org/scholia/

**Comment by Daniel-Mietchen** [comment]
I think adding a few more would be useful, e.g. total number of items and of scientific articles, and then a good selection of properties from the above list and/ or from https://www.wikidata.org/wiki/Template:Bibliographic_properties .

**Comment by fnielsen** [comment]
Added with https://github.com/fnielsen/scholia/commit/b8f8f6a496d0c8bef0f67fcb96afa31a9725cece and now running at https://tools.wmflabs.org/scholia/

**Comment by lucaswerkmeister** [comment]
Number of properties:

```sparql
SELECT (COUNT(*) AS ?propertyCount) WHERE {
  ?property a wikibase:Property.
}
```

For the number of triples, you can also use `?s ?p ?o` (**s**ubject **p**redicate **o**bject) instead of `[] ?p []` – equivalent but *slightly* more readable :)

**Comment by Daniel-Mietchen** [comment]
Thanks, @lucaswerkmeister &mdash; I've just included it in the above batch of additional stats.

**Comment by Daniel-Mietchen** [comment]
The above patch caused display problems, so we reverted it. [Here](https://query.wikidata.org/#SELECT%20%3Fcount%20%3Fdescription%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20%3Fp%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25triples%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%3Fproperty%20a%20wikibase%3AProperty.%20%20%7D%0A%7D%20AS%20%25properties%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP50%20%5B%5D.%20%7D%0A%7D%20AS%20%25authors%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP69%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25almamater%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP108%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25employer%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP166%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25award_received%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP212%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25isbn13%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP225%20%5B%5D.%20%7D%0A%7D%20AS%20%25taxa%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP234%20%5B%5D.%20%7D%0A%7D%20AS%20%25inchi%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28DISTINCT%20%3Fserials%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%3Fserials%20wdt%3AP236%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25issn%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP356%20%5B%5D.%20%7D%0A%7D%20AS%20%25dois%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP496%20%5B%5D.%20%7D%0A%7D%20AS%20%25orcids%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP625%20%5B%5D.%20%7D%0A%7D%20AS%20%25geoloc%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP638%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25pdb%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP686%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25gene%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP698%20%5B%5D.%20%7D%0A%7D%20AS%20%25pmids%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP699%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25disease%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP859%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25sponsor%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP818%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25arxivID%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP921%20%5B%5D.%20%7D%0A%7D%20AS%20%25topics%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP932%20%5B%5D.%20%7D%0A%7D%20AS%20%25pmcids%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP1416%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25affiliation%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP2093%20%5B%5D.%20%7D%0A%7D%20AS%20%25authorstrings%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP2427%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25GRID%0AWITH%20%7B%0A%20%20SELECT%20%28COUNT%28%2a%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%5B%5D%20wdt%3AP2860%20%5B%5D%20.%20%7D%0A%7D%20AS%20%25cites%0AWHERE%20%7B%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25triples%0A%20%20%20%20BIND%28%22Total%20number%20of%20triples%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25properties%0A%20%20%20%20BIND%28%22Total%20number%20of%20properties%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25pmids%0A%20%20%20%20BIND%28%22Items%20with%20a%20PubMed%20ID%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25pmcids%0A%20%20%20%20BIND%28%22Items%20with%20a%20PubMed%20Central%20ID%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25dois%0A%20%20%20%20BIND%28%22Items%20with%20a%20Digital%20Object%20Identifier%20%28DOI%29%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25cites%0A%20%20%20%20BIND%28%22Citations%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25authors%0A%20%20%20%20BIND%28%22Links%20from%20items%20about%20works%20to%20items%20about%20their%20authors%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25authorstrings%0A%20%20%20%20BIND%28%22Author%20name%20strings%20on%20items%20about%20works%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25orcids%0A%20%20%20%20BIND%28%22Items%20about%20authors%20with%20an%20ORCID%20profile%20that%20has%20public%20content%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25taxa%0A%20%20%20%20BIND%28%22Items%20with%20a%20taxon%20name%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25geoloc%0A%20%20%20%20BIND%28%22Items%20with%20a%20geolocation%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25topics%0A%20%20%20%20BIND%28%22Links%20from%20items%20about%20works%20to%20items%20about%20their%20main%20subjects%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25inchi%0A%20%20%20%20BIND%28%22Items%20with%20an%20International%20Chemical%20Identifier%20%28InChI%29%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25isbn13%0A%20%20%20%20BIND%28%22Items%20with%20a%2013-digit%20International%20Standard%20Book%20Number%20%28ISBN%2013%29%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25award_received%0A%20%20%20%20BIND%28%22Links%20from%20items%20about%20people%20or%20others%20to%20an%20award%20they%20have%20received%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25affiliation%0A%20%20%20%20BIND%28%22Links%20from%20items%20about%20people%20to%20items%20about%20groups%20they%20are%20affiliated%20with%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25employer%0A%20%20%20%20BIND%28%22Links%20from%20items%20about%20people%20to%20items%20about%20their%20employer%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25almamater%0A%20%20%20%20BIND%28%22Links%20from%20items%20about%20people%20to%20items%20about%20the%20educational%20establishments%20they%20attended%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25issn%0A%20%20%20%20BIND%28%22Items%20with%20an%20International%20Standard%20Serial%20Number%20%28ISSN%29%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25arxivID%0A%20%20%20%20BIND%28%22Items%20with%20an%20arxivID%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25GRID%0A%20%20%20%20BIND%28%22Items%20about%20institutions%20with%20an%20identifier%20from%20the%20Global%20Research%20Identifier%20Database%20%28GRID%20ID%29%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25sponsor%0A%20%20%20%20BIND%28%22Links%20from%20items%20about%20anything%20to%20items%20about%20corresponding%20sponsors%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25disease%0A%20%20%20%20BIND%28%22Items%20indexed%20in%20the%20Disease%20Ontology%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25gene%0A%20%20%20%20BIND%28%22Items%20indexed%20in%20the%20Gene%20Ontology%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%20%20UNION%0A%20%20%7B%0A%20%20%20%20INCLUDE%20%25pdb%0A%20%20%20%20BIND%28%22Protein%20structures%20indexed%20in%20the%20Protein%20Data%20Bank%22%20AS%20%3Fdescription%29%0A%20%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fcount%29) is the query again:

```SPARQL
SELECT ?count ?description
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] ?p [] . }
} AS %triples
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { ?property a wikibase:Property.  }
} AS %properties
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P50 []. }
} AS %authors
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P69 [] . }
} AS %almamater
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P108 [] . }
} AS %employer
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P166 [] . }
} AS %award_received
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P212 [] . }
} AS %isbn13
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P225 []. }
} AS %taxa
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P234 []. }
} AS %inchi
WITH {
  SELECT (COUNT(DISTINCT ?serials) AS ?count) WHERE { ?serials wdt:P236 [] . }
} AS %issn
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P356 []. }
} AS %dois
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P496 []. }
} AS %orcids
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P625 []. }
} AS %geoloc
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P638 [] . }
} AS %pdb
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P686 [] . }
} AS %gene
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P698 []. }
} AS %pmids
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P699 [] . }
} AS %disease
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P859 [] . }
} AS %sponsor
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P818 [] . }
} AS %arxivID
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P921 []. }
} AS %topics
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P932 []. }
} AS %pmcids
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P1416 [] . }
} AS %affiliation
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P2093 []. }
} AS %authorstrings
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P2427 [] . }
} AS %GRID
WITH {
  SELECT (COUNT(*) AS ?count) WHERE { [] wdt:P2860 [] . }
} AS %cites
WHERE {
  {
    INCLUDE %triples
    BIND("Total number of triples" AS ?description)
  }
  UNION
  {
    INCLUDE %properties
    BIND("Total number of properties" AS ?description)
  }
  UNION
  {
    INCLUDE %pmids
    BIND("Items with a PubMed ID" AS ?description)
  }
  UNION
  {
    INCLUDE %pmcids
    BIND("Items with a PubMed Central ID" AS ?description)
  }
  UNION
  {
    INCLUDE %dois
    BIND("Items with a Digital Object Identifier (DOI)" AS ?description)
  }
  UNION
  {
    INCLUDE %cites
    BIND("Citations" AS ?description)
  }
  UNION
  {
    INCLUDE %authors
    BIND("Links from items about works to items about their authors" AS ?description)
  }
  UNION
  {
    INCLUDE %authorstrings
    BIND("Author name strings on items about works" AS ?description)
  }
  UNION
  {
    INCLUDE %orcids
    BIND("Items about authors with an ORCID profile that has public content" AS ?description)
  }
  UNION
  {
    INCLUDE %taxa
    BIND("Items with a taxon name" AS ?description)
  }
  UNION
  {
    INCLUDE %geoloc
    BIND("Items with a geolocation" AS ?description)
  }
  UNION
  {
    INCLUDE %topics
    BIND("Links from items about works to items about their main subjects" AS ?description)
  }
  UNION
  {
    INCLUDE %inchi
    BIND("Items with an International Chemical Identifier (InChI)" AS ?description)
  }
  UNION
  {
    INCLUDE %isbn13
    BIND("Items with a 13-digit International Standard Book Number (ISBN 13)" AS ?description)
  }
  UNION
  {
    INCLUDE %award_received
    BIND("Links from items about people or others to an award they have received" AS ?description)
  }
  UNION
  {
    INCLUDE %affiliation
    BIND("Links from items about people to items about groups they are affiliated with" AS ?description)
  }
  UNION
  {
    INCLUDE %employer
    BIND("Links from items about people to items about their employer" AS ?description)
  }
  UNION
  {
    INCLUDE %almamater
    BIND("Links from items about people to items about the educational establishments they attended" AS ?description)
  }
  UNION
  {
    INCLUDE %issn
    BIND("Items with an International Standard Serial Number (ISSN)" AS ?description)
  }
  UNION
  {
    INCLUDE %arxivID
    BIND("Items with an arxivID" AS ?description)
  }
  UNION
  {
    INCLUDE %GRID
    BIND("Items about institutions with an identifier from the Global Research Identifier Database (GRID ID)" AS ?description)
  }
  UNION
  {
    INCLUDE %sponsor
    BIND("Links from items about anything to items about corresponding sponsors" AS ?description)
  }
  UNION
  {
    INCLUDE %disease
    BIND("Items indexed in the Disease Ontology" AS ?description)
  }
  UNION
  {
    INCLUDE %gene
    BIND("Items indexed in the Gene Ontology" AS ?description)
  }
  UNION
  {
    INCLUDE %pdb
    BIND("Protein structures indexed in the Protein Data Bank" AS ?description)
  }
}
ORDER BY DESC(?count)
```

Pinging @lucaswerkmeister

**Comment by lucaswerkmeister** [comment]
What kinds of display problems did it cause?

**Comment by fnielsen** [comment]
There was no response from WDQS, probably because the query was too lone. Perhaps the getJSON can be modified to a POST.

**Comment by lucaswerkmeister** [comment]
WDQS already retries using POST if the GET request fails due to being too long. If I run the query in @Daniel-Mietchen’s comment on WDQS, it works both on index.html and embed.html.

**Comment by fnielsen** [comment]
"Items about authors with an ORCID profile that has public content" Why "that has public content"?

**Comment by fnielsen** [comment]
"Items with a 13-digit International Standard Book Number (ISBN 13)" This should be rephrased as there might be items with multiple ISBN (there is, especially Springer volume).

**Comment by Daniel-Mietchen** [comment]
I have reworked the query, as per https://github.com/Daniel-Mietchen/ideas/issues/1022#issuecomment-559724135 .
