### ISSUE TITLE
Taxon ranks not sorted hierarchically

### ISSUE THREAD

**Issue by pigsonthewing** [fnielsen/scholia#340]
On, e.g., https://tools.wmflabs.org/scholia/taxon/Q25485 the parent taxon ranks are not sorted hierarchically (from "genus" to "kingdom"). Selecting the "RankList" header does not offer this sort option.

I suggest that hierarchcal sorting should be the default.

![image](https://user-images.githubusercontent.com/89541/38768954-0cf9f8de-3ff3-11e8-8df0-ab13f3177ffa.png)

**Comment by fnielsen** [comment]
This bug is the same as #239.
