### ISSUE TITLE
RSS button is missing on sponsor aspect

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#342]
e.g. https://tools.wmflabs.org/scholia/sponsor/Q48693816

**Comment by fnielsen** [comment]
There is a lot of places where RSS is missing. I regard these issues as call for enhancement, rather than a usual bug.

**Comment by egonw** [comment]
I was just about to file such an enhancement myself :)

@Daniel-Mietchen, I wanted a roll-out first to get feedback... now that we did not get negative feedback (not sure how much it is used... any chance we can see that from the logs?), it's time for me to implement it in more places...

**Comment by egonw** [comment]
In progress...
