### ISSUE TITLE
For Work also list a table with citing articles sorted by number of citations

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#35]
Like you get on Google Scholar... this is the query that can be used:

    #defaultView:Table
    SELECT ?work ?work_label (count(?citing_work) as ?count) WHERE {
      ?work wdt:P2860 wd:Q27065423 .
      ?citing_work wdt:P2860 ?work . 
      ?work rdfs:label ?work_label . filter (lang(?work_label) = 'en')
    } group by ?work ?work_label
    order by desc(?count)
    limit 20

Where you can replace wd:Q27065423 with $work

**Comment by fnielsen** [comment]
I have made an extra column, - not an extra table. I suppose that is ok? The Javascript table enables sorting https://tools.wmflabs.org/scholia/work/Q27065423

**Comment by egonw** [comment]
Sure!
