### ISSUE TITLE
[advise needed] add chemical drawing SVG in /chemical/ aspect

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#353]
For chemicals Wikidata provides SMILES, often in two forms, the isomeric one being more precise, and thus better. I like to show the 2D diagram depicted with SVG right of the Wikipedia description (if available, but to get an idea where). The SVG can be generated with the CDKDepict tool.

However, I am not sure how to best get this in the HTML generation process... 1. we need to get the SMILES for the structure (one of the two), and then 2. it needs to craft a URL, and finally, 3. that SVG is embedded in the HTML (with JavaScript or with Python) *or* the SVG URL is used with &lt;img src=".." />.

What approach would fit best with the current set up? Should we have a `scholia/query.py` method to return the (best) SMILES? Put that in an variable to be used in the HTML template?

Suggestions welcome!

**Comment by egonw** [comment]
So, (next morning), what are our options?

What if I updated the code so that with a command line option the feature is turned on? Allowing us to run an instance with this functionality (e.g. on my laptop) but not on wmflabs?
for wmflabs, so, we are stuck with online material from WikiCommons, correct?
and I can add extra option to show the compound image there, in the first place, with the SVG as optional (turned off by default) CDKDepict option

**Comment by fnielsen** [comment]
Is there no standalone library for rendering SMILES?

I suppose we could make an option for thirdparty

**Comment by egonw** [comment]
CDK can be used standalone, but is Java... is that an option?

Easier for now is an option for 3rd party installations, turned off by default, with a fall back to images given in Wikidata (image and structure diagram)... I'll try to implement this today...

**Comment by fnielsen** [comment]
You can try and pull it now and go and edit runserver.py. No fixed configuration is possible at the moment.

**Comment by fnielsen** [comment]
I will be interested to hear if there is any problems.

**Comment by egonw** [comment]
Tested and seems to work fine, thanks!
