### ISSUE TITLE
Project feature

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#354]
Aimed at linking funders to research output.

**Comment by egonw** [comment]
First steps:

![image](https://user-images.githubusercontent.com/26721/39394331-52d16944-4ad1-11e8-8d46-70fcbc22b648.png)

**Comment by fnielsen** [comment]
Yes, but do we have any Wikidata items? And a reasonable consistent ... (ok I see your example now :))

**Comment by egonw** [comment]
Making progress:

![image](https://user-images.githubusercontent.com/26721/39395056-d8301b0a-4ad9-11e8-8ee6-d2e91b51713e.png)

**Comment by egonw** [comment]
More content:

![image](https://user-images.githubusercontent.com/26721/39396280-a0b05c82-4aeb-11e8-8851-3871806c3150.png)

**Comment by egonw** [comment]
OK, and it's really enough for today:

![image](https://user-images.githubusercontent.com/26721/39396436-6168104e-4aee-11e8-9193-856517da1a06.png)

**Comment by egonw** [comment]
For a random ERC grant:

![image](https://user-images.githubusercontent.com/26721/39396733-263de9ac-4af4-11e8-937a-96c39cffa53a.png)
