### ISSUE TITLE
Rate limit exceeded for very prolific author

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#373]
https://tools.wmflabs.org/scholia/author/Q6251482

Panels may also miss content.

**Comment by Daniel-Mietchen** [comment]
That page displays fine for me but some others have problems with publications / pages per year. E.g.
- https://tools.wmflabs.org/scholia/author/Q38319111 (author)
- https://tools.wmflabs.org/scholia/organization/Q503424 (institution)

**Comment by fnielsen** [comment]
"Number of pages per year" sometimes display quite wrong content in a scatter plot like barchart.

**Comment by fnielsen** [comment]
This issue is also reported here: https://phabricator.wikimedia.org/T194735

**Comment by fnielsen** [comment]
Some solutions:
- Restrict the number of panels on each page and move some panels to subaspects.
- Delay the download with a hardcoded period
- Delay the download to visibility.
- Join panels by commons WDQS.
- Interact with the WDQS people and let them tell us about query limitation

**Comment by maxlath** [comment]
what about keeping requests results in cache?

**Comment by fnielsen** [comment]
The problem has now likely been fixed with https://phabricator.wikimedia.org/T194735
