### ISSUE TITLE
In stats panel on Scholia starting page, change default number of results shown to 25

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#376]
it's currently 10 as usual.
I'd like to add a few more stats of the kinds that are already there, and already one result is hidden behind the click required to expand the list from the default of 10.

**Comment by Daniel-Mietchen** [comment]
Actually, we have 25 now, so maybe defaulting to a larger number would make sense.

**Comment by maxlath** [comment]
fixed by #377
