### ISSUE TITLE
RSS button for /chemical/ Recent articles

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#388]
Which is currently missing: 

![image](https://user-images.githubusercontent.com/26721/40281176-29156bfc-5c5e-11e8-8bd6-a2797ed85d92.png)

**Comment by fnielsen** [comment]
Can't you just switch to the topic view and subscribed to that RSS feed?

**Comment by egonw** [comment]
Good catch... it can use the exact same URL for the feed... but having the RSS icon on /chemical/ too would be nice... for discoverability, etc... OK?
