### ISSUE TITLE
ID's should be escaped before turned to URIs

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#391]
For, e.g., https://tools.wmflabs.org/scholia/chemical/Q27124756 the InChl external link does not resolve because the ID is not escaped. This is also a security issue.

I cannot find an escaping function in Blazegraph's SPARQL.

**Comment by fnielsen** [comment]
https://stackoverflow.com/questions/50497875/escape-string-for-conversion-to-uri-in-sparql

**Comment by fnielsen** [comment]
Possible solution:
```BIND(IRI(REPLACE(?formatterurl, '\\$1', REPLACE(REPLACE(?id, "\\+", '%2B'), '/', '%2F')))```

**Comment by egonw** [comment]
We also need this for Isomeric SMILES.
