### ISSUE TITLE
On landing page for awards aspect, add examples with Nobel laureates

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#401]
e.g. something similar to https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples#Authors_of_scientific_articles_who_received_a_Nobel_prize .

**Comment by fnielsen** [comment]
This is in the award aspect you mean?

**Comment by Daniel-Mietchen** [comment]
Renamed to clarify.
