### ISSUE TITLE
RSS feed pretends to have hourly precision, when it's actually daily at best

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#432]
e.g. https://tools.wmflabs.org/scholia/topic/Q2587068/latest-works/rss

**Comment by egonw** [comment]
Daniel, what do you mean? The <pubDate> field? That's just the expected format...

Because I don't think the RSS says how frequent it gets updated...

**Comment by fnielsen** [comment]
The publication date is e.g., `<pubDate>Mon, 18 Jun 2018 00:00:00 -0000</pubDate>`. As far as I understand the RSS2 uses RFC 822. How this is suppose to be understood I do not know because RFC 822 seems only to have 2DIGIT for year. But both date and time seems necessary.

**Comment by egonw** [comment]
@fnielsen, there are too many RSS formats around :(

**Comment by egonw** [comment]
BTW, it is valid according to the W3: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftools.wmflabs.org%2Fscholia%2Ftopic%2FQ2587068%2Flatest-works%2Frss

**Comment by egonw** [comment]
@fnielsen, this validator I linked to 13 hours ago actually says it needs to be of RFC822 data-time format (with exception of 4-digit year): https://validator.w3.org/feed/docs/error/InvalidRFC2822Date.html

**Comment by fnielsen** [comment]
I would not mind me if you close it.
