### ISSUE TITLE
In work aspect, add panel for citations from Wikimedia projects

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#433]
e.g. via something like 

```SPARQL
SELECT * WHERE {
  SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:api "Search" .
      bd:serviceParam wikibase:endpoint "sw.wikipedia.org" .
      bd:serviceParam mwapi:srsearch "\"10.1038/171737a0\"" .
      ?title wikibase:apiOutput mwapi:title .
  }
} LIMIT 200

```

[Try it](https://query.wikidata.org/#SELECT%20%2a%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Amwapi%20%7B%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aapi%20%22Search%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aendpoint%20%22sw.wikipedia.org%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Asrsearch%20%22%5C%2210.1038%2F171737a0%5C%22%22%20.%0A%20%20%20%20%20%20%3Ftitle%20wikibase%3AapiOutput%20mwapi%3Atitle%20.%0A%20%20%7D%0A%7D%20LIMIT%20200)

**Comment by Daniel-Mietchen** [comment]
This approach could be of interest for other aspects too, e.g. chemical compounds, diseases, taxa.

**Comment by Daniel-Mietchen** [comment]
Works with ISBNs too:

```SPARQL
SELECT * WHERE {
  SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:api "Search" .
      bd:serviceParam wikibase:endpoint "en.wikipedia.org" .
      bd:serviceParam mwapi:srsearch "\"ISBN: 9781852337520\"" .
      ?title wikibase:apiOutput mwapi:title .
  }
} LIMIT 200
```

[Try it](https://query.wikidata.org/#SELECT%20%2a%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Amwapi%20%7B%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aapi%20%22Search%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aendpoint%20%22en.wikipedia.org%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Asrsearch%20%22%5C%22ISBN%3A%209781852337520%5C%22%22%20.%0A%20%20%20%20%20%20%3Ftitle%20wikibase%3AapiOutput%20mwapi%3Atitle%20.%0A%20%20%7D%0A%7D%20LIMIT%20200)

**Comment by fnielsen** [comment]
Available now e.g., by https://scholia.toolforge.org/work/Q21012624
