### ISSUE TITLE
Some graphs give an "Unable to display result" error only when embedded

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#441]
In
https://tools.wmflabs.org/scholia/topic/Q668 ,
the Co-author graph and the Co-occurring topics graph currently give this error, despite working fine when run separately via the "Edit this query" link.

Pinging @lucaswerkmeister

**Comment by Daniel-Mietchen** [comment]
I have now checked this for a number of topics, and these two graphs always give this error - see
https://tools.wmflabs.org/scholia/topic/Q202864 (Zika virus) for another example.

As far as I can tell, things were fine still on Sunday, so I assume some change since has brought about this behaviour.

**Comment by Daniel-Mietchen** [comment]
Opened a Phabricator ticket for this: https://phabricator.wikimedia.org/T200409 .

**Comment by fnielsen** [comment]
For one response I do not get any status code and I get JSON instead of HTML.

**Comment by fnielsen** [comment]
I suppose the embed script so the JSON type should be no surprise. The status code is strange though.

I was under the impression that it might have something to do with throttling on the WDQS side (because of the many parallel requests we are making). It is strange though that it is only the graphs where there is a problem. It is not just the topic aspect but also, e.g., the co-author graph panel in the author aspect, see, e.g., https://tools.wmflabs.org/scholia/author/Q8219 .

**Comment by fnielsen** [comment]
Ok. I see that it is taken care of on the Wikimedia Phabricator.

**Comment by Daniel-Mietchen** [comment]
The matter is resolved on their end, and they [recommend](https://phabricator.wikimedia.org/T200409#4461017) that we "should add the attributes referrerpolicy="origin" and sandbox="allow-scripts allow-same-origin allow-popups" to [our] iframe code", as per the following example
```
<iframe style="width: 80vw; height: 50vh; border: none;" src="./embed.html#%23Cats%0ASELECT%20%3Fitem%20%3FitemLabel%20%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ146.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups"></iframe>
```

**Comment by fnielsen** [comment]
This was fixed with https://phabricator.wikimedia.org/T200409
