### ISSUE TITLE
In work aspect, add citations from Wikimedia projects

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#449]
[Prototype](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20%3Ftype%20%3FtypeLabel%20WHERE%20%7B%0A%20%7B%0A%20%20%20SELECT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20SERVICE%20wikibase%3Amwapi%20%7B%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aendpoint%20%22en.wikipedia.org%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aapi%20%22Generator%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agenerator%20%22search%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrsearch%20%22insource%3A%5C%2210.1371%2Fjournal.pone.0029797%5C%22%20doi%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrlimit%20%22max%22%20.%0A%20%20%20%20%20%20%3Fitem%20wikibase%3AapiOutputItem%20mwapi%3Aitem%20.%0A%20%20%20%20%7D%0A%20%20%7D%20LIMIT%20100%0A%20%7D%0A%20hint%3APrior%20hint%3ArunFirst%20%22true%22.%0A%20%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20%3Ftype%20.%0A%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%20LIMIT%20100):

```SPARQL
SELECT ?item ?itemLabel ?type ?typeLabel WHERE {
 {
   SELECT ?item WHERE {
    SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:endpoint "en.wikipedia.org" .
      bd:serviceParam wikibase:api "Generator" .
      bd:serviceParam mwapi:generator "search" .
      bd:serviceParam mwapi:gsrsearch "insource:\"10.1371/journal.pone.0029797\" doi" .
      bd:serviceParam mwapi:gsrlimit "max" .
      ?item wikibase:apiOutputItem mwapi:item .
    }
  } LIMIT 100
 }
 hint:Prior hint:runFirst "true".
 ?item wdt:P31|wdt:P279 ?type .
 SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} LIMIT 100

```

**Comment by Daniel-Mietchen** [comment]
Actually, we should take into account things like [proximity](https://www.mediawiki.org/wiki/Help:CirrusSearch#Words,_phrases,_and_modifiers), e.g. as per [query variants like this](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20%3Ftype%20%3FtypeLabel%20WHERE%20%7B%0A%20%7B%0A%20%20%20SELECT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20SERVICE%20wikibase%3Amwapi%20%7B%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aendpoint%20%22en.wikipedia.org%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aapi%20%22Generator%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agenerator%20%22search%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrsearch%20%22insource%3Adoi~%5C%2210.1371%2Fjournal.pone.0029797%5C%22%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrlimit%20%22max%22%20.%0A%20%20%20%20%20%20%3Fitem%20wikibase%3AapiOutputItem%20mwapi%3Aitem%20.%0A%20%20%20%20%7D%0A%20%20%7D%20LIMIT%20100%0A%20%7D%0A%20hint%3APrior%20hint%3ArunFirst%20%22true%22.%0A%20%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20%3Ftype%20.%0A%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%20LIMIT%20100):

```SPARQL
SELECT ?item ?itemLabel ?type ?typeLabel WHERE {
 {
   SELECT ?item WHERE {
    SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:endpoint "en.wikipedia.org" .
      bd:serviceParam wikibase:api "Generator" .
      bd:serviceParam mwapi:generator "search" .
      bd:serviceParam mwapi:gsrsearch "insource:doi~\"10.1371/journal.pone.0029797\"" .
      bd:serviceParam mwapi:gsrlimit "max" .
      ?item wikibase:apiOutputItem mwapi:item .
    }
  } LIMIT 100
 }
 hint:Prior hint:runFirst "true".
 ?item wdt:P31|wdt:P279 ?type .
 SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} LIMIT 100
```

**Comment by Daniel-Mietchen** [comment]
For other publication identifiers, we could do similar things, e.g. [for PMID](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20%3Ftype%20%3FtypeLabel%20WHERE%20%7B%0A%20%7B%0A%20%20%20SELECT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20SERVICE%20wikibase%3Amwapi%20%7B%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aendpoint%20%22it.wikipedia.org%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aapi%20%22Generator%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agenerator%20%22search%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrsearch%20%22insource%3A%5C%2222253785%5C%22%20PMID%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrlimit%20%22max%22%20.%0A%20%20%20%20%20%20%3Fitem%20wikibase%3AapiOutputItem%20mwapi%3Aitem%20.%0A%20%20%20%20%7D%0A%20%20%7D%20LIMIT%20100%0A%20%7D%0A%20hint%3APrior%20hint%3ArunFirst%20%22true%22.%0A%20%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20%3Ftype%20.%0A%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%20LIMIT%20100):

```SPARQL
SELECT ?item ?itemLabel ?type ?typeLabel WHERE {
 {
   SELECT ?item WHERE {
    SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:endpoint "it.wikipedia.org" .
      bd:serviceParam wikibase:api "Generator" .
      bd:serviceParam mwapi:generator "search" .
      bd:serviceParam mwapi:gsrsearch "insource:\"22253785\" PMID" .
      bd:serviceParam mwapi:gsrlimit "max" .
      ?item wikibase:apiOutputItem mwapi:item .
    }
  } LIMIT 100
 }
 hint:Prior hint:runFirst "true".
 ?item wdt:P31|wdt:P279 ?type .
 SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
} LIMIT 100
```

Things are a bit more messy with PMCID, since that may occur in various forms, e.g. "pmc=3256195" or "[PMC3256195](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20%3Ftype%20%3FtypeLabel%20WHERE%20%7B%0A%20%7B%0A%20%20%20SELECT%20%3Fitem%20WHERE%20%7B%0A%20%20%20%20SERVICE%20wikibase%3Amwapi%20%7B%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aendpoint%20%22eu.wikipedia.org%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20wikibase%3Aapi%20%22Generator%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agenerator%20%22search%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrsearch%20%22insource%3A%5C%22pmc3256195%5C%22%22%20.%0A%20%20%20%20%20%20bd%3AserviceParam%20mwapi%3Agsrlimit%20%22max%22%20.%0A%20%20%20%20%20%20%3Fitem%20wikibase%3AapiOutputItem%20mwapi%3Aitem%20.%0A%20%20%20%20%7D%0A%20%20%7D%20LIMIT%20100%0A%20%7D%0A%20hint%3APrior%20hint%3ArunFirst%20%22true%22.%0A%20%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20%3Ftype%20.%0A%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%20LIMIT%20100)" or "pmcid=3256195" .

**Comment by Daniel-Mietchen** [comment]
Besides the work aspect, citations from Wikimedia might well be interesting for other aspects as well, but I'll set up a different ticket for that, so that we can concentrate on the work aspect here.

**Comment by Daniel-Mietchen** [comment]
It would of course be cool to be able to do this kind of query across Wikimedia sites, but this is [not currently possible](https://phabricator.wikimedia.org/T171303) through the SPARQL endpoint, although we could of course use the MediaWiki API directly for multiple wikis and then feed that into Scholia, either via additional SPARQL queries or directly.

**Comment by fnielsen** [comment]
It is also possible with the cite q template

```sparql
SELECT
  ?item ?itemLabel
  ?article ?articleUrl
WHERE {
 {
   SELECT ?item WHERE {
     SERVICE wikibase:mwapi {
       bd:serviceParam wikibase:endpoint "da.wikipedia.org" .
       bd:serviceParam wikibase:api "Generator" .
       bd:serviceParam mwapi:generator "search" .
       bd:serviceParam mwapi:gsrsearch "insource:\"cite q Q61715535\"" .
       bd:serviceParam mwapi:gsrlimit "max" .
       ?item wikibase:apiOutputItem mwapi:item .
     }
   } LIMIT 100
 }
 hint:Prior hint:runFirst "true".
 ?articleUrl schema:about ?item .
 ?articleUrl schema:name ?article .
 ?articleUrl schema:inLanguage "da" .
 SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
```

**Comment by fnielsen** [comment]
I suppose one could also dare to do just "Q61715535"

**Comment by fnielsen** [comment]
This seems to be the same as #433
