### ISSUE TITLE
For Venue statistics panel in author aspect, use SAMPLE(?short_name)

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#452]
Sometimes, there is more than one short name, e.g. https://www.wikidata.org/wiki/Q867727#P1813 ,
which looks odd in Scholia profiles like
https://tools.wmflabs.org/scholia/author/Q56102504 .

**Comment by Daniel-Mietchen** [comment]
Another example: https://tools.wmflabs.org/scholia/author/Q315454 .

**Comment by Daniel-Mietchen** [comment]
Another one: https://tools.wmflabs.org/scholia/author/Q38326685

**Comment by fnielsen** [comment]
Now runs: https://tools.wmflabs.org/scholia/author/Q38326685
