### ISSUE TITLE
Use QID for aspects as well

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#46]
e.g.
https://tools.wmflabs.org/scholia/Q2085381/
as an equivalent to
https://tools.wmflabs.org/scholia/publisher/ .

**Comment by fnielsen** [comment]
I am not sure that is a good idea, because a work may be about "publisher" generally, - or "work" or "chemical".

**Comment by egonw** [comment]
@Daniel-Mietchen, shall we close this one? I agree with @fnielsen that this is likely not a good idea.

**Comment by Daniel-Mietchen** [comment]
@egonw I'm not sure what @fnielsen had in mind with the comment above, or what the argument is against using QIDs for aspects (other than reduced readability for people who know English). 

My point is to make the interface more usable across languages, and the QIDs seem like a good way to go about that. I had also considered going for lexemes, but think going for the items makes more sense here.

Given that we haven't worked on this in about two years, though, I will not object to the ticket being closed, with the understanding that it can always be reopened.

**Comment by fnielsen** [comment]
I think my concern was that https://scholia.toolforge.org/Q2085381 could mean https://scholia.toolforge.org/topic/Q2085381 and not just https://scholia.toolforge.org/publisher/
