### ISSUE TITLE
In query results, provide option to replace Wikidata links with Scholia links

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#49]
Allow traveling from one Scholia page to another one by replacing - optionally - the links to Wikidata items with links to Scholia profiles.

**Comment by fnielsen** [comment]
The tables are now in a transition to use DataTables Javascript library, see, e.g., c1fdcce325c565e2acef6562f4555bf3bca03bed. It takes a while to convert them all.

**Comment by fnielsen** [comment]
For aspects:

- [ ] Author
- [ ] Work 
- [ ] Organization
- [ ] Venue
- [ ] Series
- [ ] Publisher
- [ ] Sponsor
- [ ] Award
- [ ] Topic

**Comment by fnielsen** [comment]
Every table now turned into using datatables. Venue was the last one: https://tools.wmflabs.org/scholia/venue/Q6294930
