### ISSUE TITLE
Co-author graph ignores two-author papers

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#519]
e.g. https://tools.wmflabs.org/scholia/author/Q56874524

**Comment by Daniel-Mietchen** [comment]
Seems this would fix it:

```SPARQL
#defaultView:Graph
SELECT DISTINCT ?author1 ?author1Label ?rgb ?author2 ?author2Label 
WITH {
  SELECT ?author1 ?author2 ?rgb WHERE {
    ?work wdt:P50 wd:Q56874524 .
    ?work wdt:P50 ?author1 .
    ?work wdt:P50 ?author2 .
    VALUES ?publication_type { wd:Q13442814 wd:Q571 wd:Q26973022}  # journal and conference articles, books, not (yet?) software
    ?work wdt:P31 ?publication_type .
    FILTER (?author1 != ?author2)
    ?author1 wdt:P21 ?gender1 . 
    BIND( IF(?gender1 = wd:Q6581097, "3182BD", "E6550D") AS ?rgb)
  }
} AS %result
WHERE {
  INCLUDE %result
  # Label the results 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,fr,de,ru,es,zh,jp". }
}

```

**Comment by fnielsen** [comment]
I do not understand? I see two authors on https://tools.wmflabs.org/scholia/author/Q56874524 (!?), - though one is not colored due to missing gender.

**Comment by Daniel-Mietchen** [comment]
Looks fine to me now as well. I presume it was a database lag.

**Comment by Daniel-Mietchen** [comment]
Reopening, since there is the same problem at 
https://tools.wmflabs.org/scholia/author/Q56379749 - multiple papers with the same two authors, but they do not show up in the co-author map.

**Comment by fnielsen** [comment]
Optional on gender: 

        OPTIONAL {
          ?author1 wdt:P21 ?gender1 . 
          BIND( IF(?gender1 = wd:Q6581097, "3182BD", "E6550D") AS ?rgb)
        }

**Comment by fnielsen** [comment]
The fix runs now: https://tools.wmflabs.org/scholia/author/Q56379749
