### ISSUE TITLE
Think about a logo

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#52]
In
https://www.wikidata.org/wiki/Template:Scholia ,
I have used 
https://commons.wikimedia.org/wiki/File:Sonar_tracking_of_tungsten_ball_underneath_research_vessel_for_calibration_(16824332958).jpg but this is probably not what we want in the long term.

**Comment by pigsonthewing** [comment]
We need an easily-recognisable icon, that will be recognisable, even at very small size, without accompanying text.

**Comment by fnielsen** [comment]
Attempt: Squeezed helvetica with colored "SCHOLIA"
```
\documentclass[12pt,landscape]{article}
\pdfoutput=1
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{color}
\usepackage{anyfontsize}
\usepackage{fix-cm}  
\makeatletter
\newcommand\HUGE{\@setfontsize\Huge{150}{180}}
\makeatother    

\definecolor{red}{RGB}{153,0,0}
\definecolor{green}{RGB}{51,153,102}
\definecolor{blue}{RGB}{0,102,153}

\begin{document}
\noindent\HUGE{\hspace{-1em}\textbf{{\color{red}S}\hspace{-0.20em}\color{green}C\hspace{-0.17em}\color{blue}H\hspace{-0.2em}\color{red}O\hspace{-0.2em}\color{green}L\hspace{-0.2em}\color{blue}I\hspace{-0.16em}\color{red}A}}

\end{document}
```

**Comment by fnielsen** [comment]
![helvetica-16](https://user-images.githubusercontent.com/484028/32255327-584761a0-bea7-11e7-8f56-a6c92c3dd251.png)

**Comment by Daniel-Mietchen** [comment]
We now have a SVG version of the Scholia logo [on Commons](https://commons.wikimedia.org/wiki/File:Scholia_logo.svg), as per [this tweet](https://twitter.com/larswillighagen/status/1121761878018023425).

**Comment by Daniel-Mietchen** [comment]
There is now

[![Scholia_logo.svg](https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Scholia_logo.svg/617px-Scholia_logo.svg.png)](https://commons.wikimedia.org/wiki/File:Scholia_logo.svg)
that is in use on Template:Scholia.

Perhaps good enough for now.

**Comment by carlinmack** [comment]
There is now

![logo](https://upload.wikimedia.org/wikipedia/commons/5/5b/Scholia_Logo_Improved.svg)
----
![wordmark 1](https://upload.wikimedia.org/wikipedia/commons/4/46/Scholia_logo_wordmark_1.svg)
----
![wordmark](https://upload.wikimedia.org/wikipedia/commons/3/36/Scholia_wordmark.svg)
