### ISSUE TITLE
The phrase "Highly cited works" is not good when there are no or few citations

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#543]
The phrase "Highly cited works" is not good when there are no or few citations.

**Comment by fnielsen** [comment]
This is related to aa8db993d2c8dabe0e5af64a68e2d0a90960a141, 01a774153b94b092163efd5c8dc48b09e1306f4c and 266ce8901c4b3452fdb0322a0ceccb80907dda0c

**Comment by Daniel-Mietchen** [comment]
We could change it to something like "Works ... by citation count"

**Comment by Daniel-Mietchen** [comment]
Closed with #629 .
