### ISSUE TITLE
Typo in clinical trials page

### ISSUE THREAD

**Issue by moqri** [fnielsen/scholia#560]
https://tools.wmflabs.org/scholia/clinical-trial/
Typo: Inverventions

**Comment by egonw** [comment]
It was fixed yesterday, but not uploaded to the production site yet: https://github.com/fnielsen/scholia/commit/2352f2f4658fe89f57be81da7ef2bccf7e95c145

**Comment by fnielsen** [comment]
I saw the error when I presented the new functionality for a crowd. :)

**Comment by fnielsen** [comment]
Now fixed in production: https://tools.wmflabs.org/scholia/clinical-trial/
