### ISSUE TITLE
Display DOIs in references

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#57]
and turn them into hyperlinks

**Comment by fnielsen** [comment]
I do not understand what you refer to? Bibtex?

**Comment by Daniel-Mietchen** [comment]
Yes, I mean that Scholia's BibTeX should be aware of DOIs.

**Comment by fnielsen** [comment]
Scholia already outputs DOIs to the `.bib` file. It is just a question of whether the style file wants to included it. This is an entry example from a .bib file:

```
@Article{Q21172284,
  author =   {Finn Årup Nielsen},
  title =    {{Scientific citations in Wikipedia}},
  journal =  {First Monday},
  year =     {2007},
  volume =   {12},
  number =   {},
  month =    {August},
  pages =    {},
  DOI =      {10.5210/FM.V12I8.1997},
  URL =      {http://firstmonday.org/article/view/1997/1872},
  wikidata = {Q21172284}
}
```

**Comment by Daniel-Mietchen** [comment]
OK, thanks - hadn't looked in the style file yet.
