### ISSUE TITLE
Random author button is not nearly random

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#586]
I just hit it 10 times in a row and got only two different authors out of that.

**Comment by fnielsen** [comment]
Just hit 4 times and got four different.

**Comment by fnielsen** [comment]
I suppose there could be the WDQS cache.

Another solution is to remove it altogether.

**Comment by fnielsen** [comment]
It is also far too slow

**Comment by fnielsen** [comment]
```python 
>>> " ".join("wd:Q{}".format(random.randrange(1, 100000000)) for _ in range(100))
```
Followed by 

```
SELECT ?author {
  VALUES ?work { wd:Q4099960 wd:Q90869473 wd:Q89343981 wd:Q59018288 w...
  ?work wdt:P50 ?author .
}
LIMIT 1
```

**Comment by fnielsen** [comment]
Now running: https://scholia.toolforge.org/author/random
