### ISSUE TITLE
"Authored works with missing topics" links works to a /author/ URL

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#607]
i.e. in
https://tools.wmflabs.org/scholia/author/Q8219/missing
it links to 
https://tools.wmflabs.org/scholia/author/Q22242672
instead of 
https://tools.wmflabs.org/scholia/work/Q22242672

The SPARQL query looks OK (though I have a suggestion for improvement in #574 ), so I suppose it's a JavaScript issue.

**Comment by egonw** [comment]
Confirmed. The solutions seems to be to set link prefixes, like here:

```javascript
sparqlToDataTable(listOfEventsSparql, "#list-of-events", {
         linkPrefixes:{
             "event": "../event/",
             "proceedings": "../venue/",
         }
     });
```

**Comment by egonw** [comment]
Confirmed. Making the patch.
