### ISSUE TITLE
The navigation buttons on an aspect's missing page currently link to nonexisting pages

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#613]
Example:
https://tools.wmflabs.org/scholia/venue/Q15749954/missing 
links to
https://tools.wmflabs.org/scholia/venue/venue/Q15749954 .

The behaviour is similar in other aspects, and I think we already have a ticket for that, but could not find it right now.

**Comment by Daniel-Mietchen** [comment]
Another example: 
https://tools.wmflabs.org/scholia/topic/Q3326411/missing
links to 
https://tools.wmflabs.org/scholia/topic/topic/Q3326411
and
https://tools.wmflabs.org/scholia/topic/work/Q3326411 
due to the relative links in
https://github.com/fnielsen/scholia/blob/master/scholia/app/templates/topic_base.html .

**Comment by fnielsen** [comment]
Yes. This is a general problem on the missing pages

**Comment by Daniel-Mietchen** [comment]
Closing as duplicate of #439
