### ISSUE TITLE
Add link for opentrials-ID in data panel of clinical trials aspect

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#621]
Add link for opentrials-ID in data panel of clinical trials aspect.

For instance, in https://tools.wmflabs.org/scholia/clinical-trial/Q58849937 the Data table should have a link to https://explorer.opentrials.net/trials/250b8bf0-e1cf-11e6-b886-0242ac120006

**Comment by Daniel-Mietchen** [comment]
I just went to 
https://explorer.opentrials.net/trials/250b8bf0-e1cf-11e6-b886-0242ac120006
and from there to their feedback form for the page, where I left the following message:

> A search via https://explorer.opentrials.net/search?q=Selumetinib does not bring up the page (even though the term is in the title of the trial), and search seems broken in general, so it would be helpful to know to what extent your project is still active, and what the plans are for the near future. In more concrete terms, I plan to work on https://github.com/fnielsen/scholia/issues/621 but cannot say right now whether that actually makes sense from your perspective.

**Comment by fnielsen** [comment]
Implemented with https://github.com/fnielsen/scholia/commit/70069dbbec4a32cdf36fb7fb8ca6b81c62f028d4

Sorry, I didn't see "I plan to work on #621 but cannot say right ..." before I had implemented it.

**Comment by fnielsen** [comment]
Now running at: https://tools.wmflabs.org/scholia/clinical-trial/Q58849937
