### ISSUE TITLE
HTTP 500 for some Scholia pages

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#631]
WMFlabs has had performance issues lately, but they did not seem to affect Scholia in particular.

Since this weekend, though, I noticed that a good number of Scholia requests get HTTP 500 responses.

Some examples that failed for me some minutes ago:
https://tools.wmflabs.org/scholia/Q4693015
https://tools.wmflabs.org/scholia/Q1223539
https://tools.wmflabs.org/scholia/Q5534494

Other pages did display properly, e.g.
https://tools.wmflabs.org/scholia/author/Q18618629 .

**Comment by Daniel-Mietchen** [comment]
Trying it a few minutes later worked, so this may be just temporary hickups.

**Comment by Daniel-Mietchen** [comment]
Right now, I am also getting "Server error" messages like

```
<html><head><title>Error 503 Service Unavailable</title></head><body><h1>503 Service Unavailable</h1>The service is temporary down for maintenance. Please check back a bit later.</body></html>

```

for some queries, e.g. "Number of publications per year" in https://tools.wmflabs.org/scholia/author/Q4693015 or "Topic scores" in https://tools.wmflabs.org/scholia/author/Q1223539 . Some other panels are affected too, but most display normally, so the maintenance may affect just a subset of the WDQS servers.

**Comment by fnielsen** [comment]
Yeah, it seems Quickstatements are also running 500-ish errors these days

**Comment by Daniel-Mietchen** [comment]
I just checked all the above-mentioned links again, and they worked fine. Closing.
