### ISSUE TITLE
gender color may be incorrect for "unknown value" in co-author graphs

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#680]
Perhaps new, but there are "unknown value" genders in Wikidata:

![image](https://user-images.githubusercontent.com/26721/56492863-59e94f80-64ed-11e9-9153-652307282b18.png)

However, this results in a colored note in the co-author graphs:

![image](https://user-images.githubusercontent.com/26721/56492901-7d13ff00-64ed-11e9-8db4-4f0b48b61a67.png)

**Comment by fnielsen** [comment]
This is a duplicate of #668

**Comment by egonw** [comment]
Oh, sorry. I had looked (IIRC), but clearly missed this one.
