### ISSUE TITLE
Acknowledge support from the Alfred P. Sloan Foundation on the Scholia website

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#682]
under grant number G-2019-11458.

**Comment by Daniel-Mietchen** [comment]
Further details are in the grant agreement, but this is in a PDF format that does not allow any meaningful copypasting.

**Comment by Daniel-Mietchen** [comment]
Pinging #669 for tracking .

**Comment by Daniel-Mietchen** [comment]
So here are the relevant text bits from the grant agreement (I keyed them in from the original, so there may be some glitches still &mdash; worth a check later on):

> "As a condition for granting an interview for any Foundation-supported project, grantees are responsible for assuring in advance that Foundation support is explicitly acknowledged in any print or online publication or in any other media. Please see the General Conditions, Article 11, for specific guidelines."

> "In all correspondence with us concerning this grant, reference should be made to the grant number assigned by the Foundation. As part of our follow-up process, we would like to receive copies of articles and press releases relating to this project or the principal investigator."

> "11. **Acknowledgment of Support**: The grantee will acknowledge the Foundation and its contribution to the project supported by the grant (the \*Project\*) in any materials (in any media) produced in connection with the Project (\*Materials\*) and in any public statements made regarding the Project, including but not limited to interviews, speeches, press releases, Web site announcements and publications (\*Media Releases\*). The grantee agrees to establish the Foundation's acknowledgment rule prior to interviews or other promotional efforts. The grantee also agrees to provide the Foundation the form of its acknowledgment in all Materials and Media Releases prior to distribution of any Materials or Media Release. Acknowledgement in all Media Releases and Materials will refer to the Foundation by its full name \*Alfred P. Sloan Foundation.\*"

"

**Comment by egonw** [comment]
"This project has received funding from the Alfred P. Sloan Foundation under grant number XXXX."

**Comment by Daniel-Mietchen** [comment]
I added this to the FAQ page: https://github.com/fnielsen/scholia/commit/2f63f7d006a7b2241b53a2a5f3142fb6ab605d49#diff-b08db88852ca7bf0de8fdd6cb58e4cf8

**Comment by Daniel-Mietchen** [comment]
The change is now live on https://tools.wmflabs.org/scholia/faq . Closing.
