### ISSUE TITLE
create a Wikidata property proposal for Alfred P. Sloan Foundation grant identifiers

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#705]

**Comment by pigsonthewing** [comment]
I'm happy to handle this, if you wish, so long as you can provide (at least) three example links.

**Comment by egonw** [comment]
Well, the database is here: https://sloan.org/grants-database

**Comment by egonw** [comment]
https://www.wikidata.org/wiki/Wikidata:Property_proposal/Alfred_P._Sloan_Foundation_Grant_ID

**Comment by egonw** [comment]
@fnielsen, you're quite right with your comment about grant versus project. The domain should indeed be grant and I'm fixing that right now. The Berlin did materialize into this (but I also only learned about that recently): https://dcodings.github.io/DINGO/

**Comment by fnielsen** [comment]
They changed the name so I couldn't find it. It was orginally called DIEGO by the others I suppose :). To me it will be DIEGO

**Comment by egonw** [comment]
Okay, I'm done updating the proposal to align much better with DINGO.

**Comment by Daniel-Mietchen** [comment]
As we cannot create this property ourselves, I am renaming this ticket to "Create property proposal"

**Comment by Daniel-Mietchen** [comment]
As the proposal has been created at 
https://www.wikidata.org/wiki/Wikidata:Property_proposal/Alfred_P._Sloan_Foundation_Grant_ID
and is under discussion there, I am closing this ticket.
