### ISSUE TITLE
Co-author graph in the topic aspect is slow

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#733]
Co-author graph in the topic aspect is slow, see, e.g., https://tools.wmflabs.org/scholia/topic/Q311383

This problem has also occurred in other aspects, see, e.g., #533

**Comment by Daniel-Mietchen** [comment]
For some topics like [Parkinson's disease](https://tools.wmflabs.org/scholia/topic/Q11085), the graph now stalls completely.

I tried to curb that by modifying the query such that it only exposes the most salient co-authorship connections, but [in the current version](https://query.wikidata.org/#%23defaultView%3AGraph%0ASELECT%20%3Fauthor1%20%3Fauthor1Label%20%3Frgb%20%3Fauthor2%20%3Fauthor2Label%0AWITH%20%7B%0A%20%20%23%20Find%20works%20with%20the%20topic%0A%20%20SELECT%20%3Fwork%20WHERE%20%7B%0A%20%20%20%20%3Fwork%20wdt%3AP921%20%2F%20%28wdt%3AP31%2a%20%2F%20wdt%3AP279%2a%20%7C%20wdt%3AP361%2B%20%7C%20wdt%3AP1269%2B%29%20wd%3AQ11085%20.%0A%20%20%7D%0A%7D%20AS%20%25works%0AWITH%20%7B%0A%20%20%23%20Limit%20the%20number%20of%20authors%0A%20%20SELECT%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount1%29%20%3Fauthor1%20WHERE%20%7B%0A%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20%3Fwork%20wdt%3AP50%20%3Fauthor1%20.%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fauthor1%0A%20%20ORDER%20BY%20DESC%28%3Fcount1%29%0A%20%20LIMIT%2010%0A%7D%20AS%20%25authors1%0AWITH%20%7B%0A%20%20%23%20Limit%20the%20number%20of%20authors%0A%20%20SELECT%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount2%29%20%3Fauthor2%20WHERE%20%7B%0A%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20INCLUDE%20%25authors1%0A%20%20%20%20%3Fwork%20wdt%3AP50%20%3Fauthor1%20%2C%20%3Fauthor2%20.%0A%20%20%20%20FILTER%20%28%3Fauthor1%20%21%3D%20%3Fauthor2%29%20%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fauthor2%0A%20%20ORDER%20BY%20DESC%28%3Fcount2%29%0A%20%20LIMIT%2010%0A%7D%20AS%20%25authors2%0AWHERE%20%7B%0A%20%20INCLUDE%20%25works%0A%20%20INCLUDE%20%25authors1%0A%20%20INCLUDE%20%25authors2%0A%20%20OPTIONAL%20%7B%20%3Fauthor1%20wdt%3AP21%20%3Fgender1%20.%20%7D%0A%20%20BIND%28%20IF%28%3Fgender1%20%3D%20wd%3AQ6581097%2C%20%223182BD%22%2C%20%22E6550D%22%29%20AS%20%3Frgb%29%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cfr%2Cde%2Cru%2Ces%2Czh%2Cjp%22.%0A%20%20%7D%0A%7D%0A), this times out:

```SPARQL
#defaultView:Graph
SELECT ?author1 ?author1Label ?rgb ?author2 ?author2Label
WITH {
  # Find works with the topic
  SELECT ?work WHERE {
    ?work wdt:P921 / (wdt:P31* / wdt:P279* | wdt:P361+ | wdt:P1269+) wd:Q11085 .
  }
} AS %works
WITH {
  # Limit the number of authors
  SELECT (COUNT(?work) AS ?count1) ?author1 WHERE {
    INCLUDE %works
    ?work wdt:P50 ?author1 .
  }
  GROUP BY ?author1
  ORDER BY DESC(?count1)
  LIMIT 10
} AS %authors1
WITH {
  # Limit the number of authors
  SELECT (COUNT(?work) AS ?count2) ?author2 WHERE {
    INCLUDE %works
    INCLUDE %authors1
    ?work wdt:P50 ?author1 , ?author2 .
    FILTER (?author1 != ?author2) 
  }
  GROUP BY ?author2
  ORDER BY DESC(?count2)
  LIMIT 10
} AS %authors2
WHERE {
  INCLUDE %works
  INCLUDE %authors1
  INCLUDE %authors2
  OPTIONAL { ?author1 wdt:P21 ?gender1 . }
  BIND( IF(?gender1 = wd:Q6581097, "3182BD", "E6550D") AS ?rgb)
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,fr,de,ru,es,zh,jp".
  }
}

```

**Comment by Daniel-Mietchen** [comment]
I slightly modified the above query (mainly dropping the ```INCLUDE %works``` line), and it now seems to work also for busy topics. I played with the LIMITs a bit and think the combination 25 for author1 and 250 for author2 works fine.

So [here](https://query.wikidata.org/#%23defaultView%3AGraph%0ASELECT%20%3Fauthor1%20%3Fauthor1Label%20%3Frgb%20%3Fauthor2%20%3Fauthor2Label%0AWITH%20%7B%0A%20%20%23%20Find%20works%20with%20the%20topic%0A%20%20SELECT%20%3Fwork%20WHERE%20%7B%0A%20%20%20%20%3Fwork%20wdt%3AP921%20%2F%20%28wdt%3AP31%2a%20%2F%20wdt%3AP279%2a%20%7C%20wdt%3AP361%2B%20%7C%20wdt%3AP1269%2B%29%20wd%3AQ11085%20.%0A%20%20%7D%0A%7D%20AS%20%25works%0AWITH%20%7B%0A%20%20%23%20Limit%20the%20number%20of%20authors%0A%20%20SELECT%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount1%29%20%3Fauthor1%20WHERE%20%7B%0A%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20%3Fwork%20wdt%3AP50%20%3Fauthor1%20.%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fauthor1%0A%20%20ORDER%20BY%20DESC%28%3Fcount1%29%0A%20%20LIMIT%2025%0A%7D%20AS%20%25authors1%0AWITH%20%7B%0A%20%20%23%20Limit%20the%20number%20of%20coauthors%0A%20%20SELECT%20DISTINCT%20%3Fauthor2%20%3Fauthor1%20%20%28COUNT%28%3Fwork%29%20AS%20%3Fcount2%29%20%20WHERE%20%7B%0A%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20INCLUDE%20%25authors1%0A%20%20%20%20%3Fwork%20wdt%3AP50%20%3Fauthor1%20%2C%20%3Fauthor2%20.%0A%20%20%20%20FILTER%20%28%3Fauthor1%20%21%3D%20%3Fauthor2%29%20%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fauthor2%20%3Fauthor1%20%0A%20%20ORDER%20BY%20DESC%28%3Fcount2%29%0A%20%20LIMIT%20250%0A%7D%20AS%20%25authors2%0AWHERE%20%7B%0A%23%20%20INCLUDE%20%25authors1%0A%20%20INCLUDE%20%25authors2%0A%20%20OPTIONAL%20%7B%20%3Fauthor1%20wdt%3AP21%20%3Fgender1%20.%20%7D%0A%20%20BIND%28%20IF%28%3Fgender1%20%3D%20wd%3AQ6581097%2C%20%223182BD%22%2C%20%22E6550D%22%29%20AS%20%3Frgb%29%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%0A%20%20%20%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cfr%2Cde%2Cru%2Ces%2Czh%2Cjp%22.%0A%20%20%7D%0A%7D%0A) is the modified version:

```SPARQL
#defaultView:Graph
SELECT ?author1 ?author1Label ?rgb ?author2 ?author2Label
WITH {
  # Find works with the topic
  SELECT ?work WHERE {
    ?work wdt:P921 / (wdt:P31* / wdt:P279* | wdt:P361+ | wdt:P1269+) wd:Q11085 .
  }
} AS %works
WITH {
  # Limit the number of authors
  SELECT (COUNT(?work) AS ?count1) ?author1 WHERE {
    INCLUDE %works
    ?work wdt:P50 ?author1 .
  }
  GROUP BY ?author1
  ORDER BY DESC(?count1)
  LIMIT 25
} AS %authors1
WITH {
  # Limit the number of coauthors
  SELECT DISTINCT ?author2 ?author1  (COUNT(?work) AS ?count2)  WHERE {
    INCLUDE %works
    INCLUDE %authors1
    ?work wdt:P50 ?author1 , ?author2 .
    FILTER (?author1 != ?author2) 
  }
  GROUP BY ?author2 ?author1 
  ORDER BY DESC(?count2)
  LIMIT 250
} AS %authors2
WHERE {
#  INCLUDE %authors1
  INCLUDE %authors2
  OPTIONAL { ?author1 wdt:P21 ?gender1 . }
  BIND( IF(?gender1 = wd:Q6581097, "3182BD", "E6550D") AS ?rgb)
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,fr,de,ru,es,zh,jp".
  }
}

```

**Comment by Daniel-Mietchen** [comment]
The above commit had an encoding problem, which was fixed with https://github.com/fnielsen/scholia/commit/bb2ee219a259c3dc3ce9d7b4c3acf572b047e600#diff-04a29c3a9ff21a4d023f710f69057842 . Looks good to me now.

**Comment by Daniel-Mietchen** [comment]
Deployed now. Closing.
