### ISSUE TITLE
create projects for 2019-20 Sloan special requests

### ISSUE THREAD

**Issue by bluerasberry** [fnielsen/scholia#746]
In the "Robustifying Scholia" proposal for 2019-20 the team wrote six categories of goals as described at #669.

Sloan the sponsor further suggested two additional goals beyond those original six. Their goals were

- At least doubling of both total users and depth of engagement metrics (e.g. number of pages/queries per session) within six months of launch
- Continued integration of Scholia visualizations into Wikipedia pages and other information resources

These two should be made into projects titled

- double select 2019 metrics by early 2020

- integrate access to Scholia into Wikipedia articles and elsewhere

**Comment by bluerasberry** [comment]
for the "double select metrics" project, here is a description:

Scholia was established in October 2016 and has been experimental till now. Because of this driving user traffic has not been a goal. We expect that there are few regular users, perhaps 50. Whatever the case, we need to count the userbase somehow, and we need to make an initial effort to grow it. The challenge here should not be in recruitment specifically, but instead to establish early usage metrics and to document a cautious effort in outreach.

For this project identify and measure Scholia's community, including a count of contributors of code, contributors of content, users who perform at least 1 query, average number of queries per user session, and number of users who return to the tool after 1 month. When possible measure with data; when not possible do a simple initial survey among the organizers asking them for their guesses. Mark what is data-based, what is a guess, and what is some of both.

**Comment by bluerasberry** [comment]
for the "integrate access to Scholia" project here is a description:

Currently most users access Scholia by navigating to the Scholia homepage. The longer term intent is that Scholia is a tool which complements other research workflows, and because of this, we need to make Scholia accessible wherever users are doing relevant research. This includes in Wikipedia articles, and for example, there could be a link or button to Scholia on the biography of a scientist which links to their Scholia profile and list of publications.

Some Wikipedia language communities, like those for English, German, French, and certain other more developed projects, are cautious about adopting new features. Other Wikipedia language communities, like the experimental Swedish language community and many smaller Wikipedias, are more willing to adopt new technology to get quicker better access to content despite bugs in code and less-reviewed information.

For this project identify a strategy of making Scholia accessible outside of its own platform and document the same. This should include experimental and documented integration into some languages of Wikipedias in some classes of articles. In addition to distribution through Wikipedia, experiment with the sharing of Scholia links in any other public platforms. In selecting other platforms, consider that the ideal outlet will be one where it is possible to measure and observe a user response.

**Comment by Daniel-Mietchen** [comment]
These now exist as 
- https://github.com/fnielsen/scholia/projects/31 for "double select metrics" 
- https://github.com/fnielsen/scholia/projects/32 for "integrate access to Scholia"
