### ISSUE TITLE
bluerasberry seeks userrights in fnielsen/scholia

### ISSUE THREAD

**Issue by bluerasberry** [fnielsen/scholia#750]
tickets would enable bluerasberry to create labels, projects, and milestones in collaboration with @Daniel-Mietchen 

This request is particularly for @fnielsen

**Comment by fnielsen** [comment]
I have invited @bluerasberry

**Comment by Daniel-Mietchen** [comment]
Thanks, Finn.
Testwise, I am assigning this ticket to Lane so he can close it.

**Comment by Daniel-Mietchen** [comment]
I just tried to assign #768 to @bluerasberry but did not have that option.

**Comment by fnielsen** [comment]
@bluerasberry needs to accept the invitation
