### ISSUE TITLE
"Not Found" for /inchikey/ could show possible related hits

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#787]
Using the 'related compounds' on the /chemical/ aspect. Right now, all we get is:

![image](https://user-images.githubusercontent.com/26721/61560194-e616fe80-aa6b-11e9-925a-41d2a54c86f5.png)

**Comment by Daniel-Mietchen** [comment]
What kind of relatedness would you like to use her?
is it something specific or should we go for something generic like Wembedder for that?

**Comment by egonw** [comment]
I was just thinking of adding this lot here, which is based on the first layer of the InChIKey:

![image](https://user-images.githubusercontent.com/26721/61575783-68d1a500-aad0-11e9-8da5-28eeb3f86b94.png)

But I need to explore first if the 404 can do "redirect"-specific page content.

**Comment by egonw** [comment]
Just for reference, this is the link https://tools.wmflabs.org/scholia/inchikey/OXKYBEZXRLIPKC-TVQITDKDNA-N

**Comment by egonw** [comment]
I had a first go at this, but still need to figure out how to get the 404 page to know the InChIKey that was being searched on. See https://github.com/fnielsen/scholia/compare/master...egonw:feature/smarterNotFound?expand=1

**Comment by egonw** [comment]
Oh, I just figured it out!

**Comment by egonw** [comment]
New "404" output looks like:

![image](https://user-images.githubusercontent.com/26721/84041072-b0407880-a9a3-11ea-9ed1-a86edc110cc7.png)

**Comment by egonw** [comment]
Patch has been applied.
