### ISSUE TITLE
Wikimania submission?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#79]
Are you going to Wikimania? Do you plan to submit anything around Scholia?

**Comment by fnielsen** [comment]
I haven't planned. It is a bit far away.

**Comment by fnielsen** [comment]
There is a related WikiCite submission here https://wikimania2017.wikimedia.org/wiki/Submissions/WikiCite_%E2%80%94_Citations_needed_for_the_sum_of_all_human_knowledge
