### ISSUE TITLE
Rethink ?next_year limit in "Number of publications/ pages per year"

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#80]
Not sure we need the ```?next year``` construct in these queries, though I understand that some publishers use dates in the future, usually to indicate when the printed version is going to come out.

In any case, the matter gets a bit messy for people who have not published in a while, e.g. [Charles Darwin](https://tools.wmflabs.org/scholia/author/Q1035).

Perhaps better go for the latest publication date as the limit, akin to 
```select (min(?year_) as ?earliest_year)``` ?

**Comment by Daniel-Mietchen** [comment]
Here are the fixed queries for Darwin:

- [Number of publications](https://query.wikidata.org/#%23defaultView%3ABarChart%0A%23%20Inspired%20from%20LEGOLAS%20-%20http%3A%2F%2Fabel.lis.illinois.edu%2Flegolas%2F%0A%23%20Shubhanshu%20Mishra%2C%20Vetle%20Torvik%0Aselect%20%3Fyear%20%28count%28%3Fwork%29%20as%20%3Fnumber_of_publications%29%20%3Frole%20where%20%7B%0A%20%20%7B%0A%20%20%20%20select%20%28str%28%3Fyear_%29%20as%20%3Fyear%29%20%280%20as%20%3Fpages%29%20%28%22_%22%20as%20%3Frole%29%20where%20%7B%0A%20%20%20%20%20%20%23%20default%20values%20%3D%200%0A%20%20%20%20%20%20%3Fyear_item%20wdt%3AP31%20wd%3AQ577%20.%20%0A%20%20%20%20%20%20%3Fyear_item%20wdt%3AP585%20%3Fdate%20.%0A%20%20%20%20%20%20bind%28year%28%3Fdate%29%20as%20%3Fyear_%29%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20select%20%28min%28%3Fyear_%29%20as%20%3Fearliest_year%29%20%20%28max%28%3Fyear_%29%20as%20%3Flatest_year%29%20where%20%7B%0A%20%20%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP50%20wd%3AQ1035%20.%0A%20%20%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP577%20%3Fpublication_date%20.%20%0A%20%20%20%20%20%20%20%20%20%20bind%28year%28%3Fpublication_date%29%20as%20%3Fyear_%29%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20bind%28year%28now%28%29%29%2B1%20as%20%3Fnext_year%29%0A%20%20%20%20%20%20filter%20%28%3Fyear_%20%3E%3D%20%3Fearliest_year%20%26%26%20%3Fyear_%20%3C%3D%20%3Flatest_year%29%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20union%20%7B%0A%20%20%7B%0A%20%20%20%20select%20%3Fwork%20%28min%28%3Fyears%29%20as%20%3Fyear%29%20%28count%28%3Fcoauthors%29%20as%20%3Fnumber_of_authors%29%20%3Fauthor_number%20where%20%7B%0A%20%20%20%20%20%20%3Fwork%20%28p%3AP50%7Cp%3AP2093%29%20%3Fauthor_statement%20.%20%0A%20%20%20%20%20%20%3Fauthor_statement%20ps%3AP50%20wd%3AQ1035%20.%0A%20%20%20%20%20%20optional%20%7B%20%3Fauthor_statement%20pq%3AP1545%20%3Fauthor_number%20.%20%7D%0A%20%20%20%20%20%20%3Fwork%20%28wdt%3AP50%7Cwdt%3AP2093%29%20%3Fcoauthors%20.%20%0A%20%20%20%20%20%20%3Fwork%20wdt%3AP577%20%3Fdates%20.%0A%20%20%20%20%20%20bind%28str%28year%28%3Fdates%29%29%20as%20%3Fyears%29%20.%0A%20%20%20%20%7D%0A%20%20%20%20group%20by%20%3Fwork%20%3Fauthor_number%0A%20%20%7D%0A%20%20bind%28coalesce%28if%28%3Fnumber_of_authors%20%3D%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%27Solo%20author%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20if%28xsd%3Ainteger%28%3Fauthor_number%29%20%3D%201%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27First%20author%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%28xsd%3Ainteger%28%3Fauthor_number%29%20%3D%20%3Fnumber_of_authors%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27Last%20author%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27Middle%20author%27%29%29%29%2C%20%27Unknown%27%29%0A%20%20%20%20%20%20%20as%20%3Frole%29%0A%20%20%20%7D%0A%7D%0Agroup%20by%20%3Fyear%20%3Frole%0Aorder%20by%20%3Fyear)

``` SPARQL
#defaultView:BarChart
# Inspired from LEGOLAS - http://abel.lis.illinois.edu/legolas/
# Shubhanshu Mishra, Vetle Torvik
select ?year (count(?work) as ?number_of_publications) ?role where {
  {
    select (str(?year_) as ?year) (0 as ?pages) ("_" as ?role) where {
      # default values = 0
      ?year_item wdt:P31 wd:Q577 . 
      ?year_item wdt:P585 ?date .
      bind(year(?date) as ?year_)
      {
        select (min(?year_) as ?earliest_year)  (max(?year_) as ?latest_year) where {
          ?work wdt:P50 wd:Q1035 .
          ?work wdt:P577 ?publication_date . 
          bind(year(?publication_date) as ?year_)
        }
      }
      bind(year(now())+1 as ?next_year)
      filter (?year_ >= ?earliest_year && ?year_ <= ?latest_year)
    }
  }
  union {
  {
    select ?work (min(?years) as ?year) (count(?coauthors) as ?number_of_authors) ?author_number where {
      ?work (p:P50|p:P2093) ?author_statement . 
      ?author_statement ps:P50 wd:Q1035 .
      optional { ?author_statement pq:P1545 ?author_number . }
      ?work (wdt:P50|wdt:P2093) ?coauthors . 
      ?work wdt:P577 ?dates .
      bind(str(year(?dates)) as ?years) .
    }
    group by ?work ?author_number
  }
  bind(coalesce(if(?number_of_authors = 1,
            'Solo author',
            if(xsd:integer(?author_number) = 1,
               'First author',
               if(xsd:integer(?author_number) = ?number_of_authors,
                  'Last author',
                  'Middle author'))), 'Unknown')
       as ?role)
   }
}
group by ?year ?role
order by ?year
```

- [Number of pages](https://query.wikidata.org/#%23defaultView%3ABarChart%0Aselect%20%3Fyear%20%3Fnumber_of_pages%20%3Fwork_label%20where%20%7B%0A%20%20%7B%0A%20%20%20%20select%20%3Fyear%20%28sample%28%3Fpages%29%20as%20%3Fnumber_of_pages%29%20%3Fwork_label%20where%20%7B%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20select%20%28str%28%3Fyear_%29%20as%20%3Fyear%29%20%280%20as%20%3Fpages%29%20%28%22_%22%20as%20%3Fwork_label%29%20where%20%7B%0A%20%20%20%20%20%20%20%20%20%20%3Fyear_item%20wdt%3AP31%20wd%3AQ577%20.%20%0A%20%20%20%20%20%20%20%20%20%20%3Fyear_item%20wdt%3AP585%20%3Fdate%20.%0A%20%20%20%20%20%20%20%20%20%20bind%28year%28%3Fdate%29%20as%20%3Fyear_%29%0A%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20select%20%28min%28%3Fyear_%29%20as%20%3Fearliest_year%29%20%28max%28%3Fyear_%29%20as%20%3Flatest_year%29%20where%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP50%20wd%3AQ1035%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP577%20%3Fpublication_date%20.%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20bind%28year%28%3Fpublication_date%29%20as%20%3Fyear_%29%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20filter%20%28%3Fyear_%20%3E%3D%20%3Fearliest_year%20%26%26%20%3Fyear_%20%3C%3D%20%3Flatest_year%29%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20union%20%7B%0A%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP50%20wd%3AQ1035%20.%0A%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP1104%20%3Fpages%20.%0A%20%20%20%20%20%20%20%20%3Fwork%20wdt%3AP577%20%3Fdate%20.%20%0A%20%20%20%20%20%20%20%20%3Fwork%20rdfs%3Alabel%20%3Flong_work_label%20.%20filter%28lang%28%3Flong_work_label%29%20%3D%20%27en%27%29%0A%20%20%20%20%20%20%20%20bind%28substr%28%3Flong_work_label%2C%201%2C%2020%29%20as%20%3Fwork_label%29%0A%20%20%20%20%20%20%20%20bind%28str%28year%28%3Fdate%29%29%20as%20%3Fyear%29%20%0A%20%20%20%20%20%20%7D%0A%09%7D%20%0A%09group%20by%20%3Fyear%20%3Fwork%20%3Fwork_label%0A%09order%20by%20%3Fyear%20%0A%20%20%7D%0A%7D)

``` SPARQL
#defaultView:BarChart
select ?year ?number_of_pages ?work_label where {
  {
    select ?year (sample(?pages) as ?number_of_pages) ?work_label where {
      {
        select (str(?year_) as ?year) (0 as ?pages) ("_" as ?work_label) where {
          ?year_item wdt:P31 wd:Q577 . 
          ?year_item wdt:P585 ?date .
          bind(year(?date) as ?year_)
          {
            select (min(?year_) as ?earliest_year) (max(?year_) as ?latest_year) where {
              ?work wdt:P50 wd:Q1035 .
              ?work wdt:P577 ?publication_date . 
              bind(year(?publication_date) as ?year_)
            }
          }
          filter (?year_ >= ?earliest_year && ?year_ <= ?latest_year)
        }
      }
      union {
        ?work wdt:P50 wd:Q1035 .
        ?work wdt:P1104 ?pages .
        ?work wdt:P577 ?date . 
        ?work rdfs:label ?long_work_label . filter(lang(?long_work_label) = 'en')
        bind(substr(?long_work_label, 1, 20) as ?work_label)
        bind(str(year(?date)) as ?year) 
      }
	} 
	group by ?year ?work ?work_label
	order by ?year 
  }
}
```

Note that GitHub doesn't properly highlight SPARQL syntax when written in lower case, as discussed at https://github.com/peta/turtle.tmbundle/issues/12 .

**Comment by fnielsen** [comment]
The reason for ?next year was that in in 2016 I have dates in the future.

**Comment by Daniel-Mietchen** [comment]
My patch should cover that, as it takes the maximum.

**Comment by fnielsen** [comment]
This should be working now, see, e.g., https://tools.wmflabs.org/scholia/author/Q1035
