### ISSUE TITLE
How does Scholia connect to Wikidata?

### ISSUE THREAD

**Issue by MorganeAlinai** [fnielsen/scholia#806]
Dear,

I was wondering, how do you gather data from Wikidata? Is it from the API, through PyWikiBot?

I had [a question related to this](https://www.quora.com/unanswered/What-are-the-best-approachs-to-embed-Wikidata-metadatas-in-a-website-so-that-it-dynamically-load-fresh-data-when-the-user-want-to-explore-a-new-concept), since I'm thinking into embeding some Wikidata into a website. However I don't know if this is a good practice to query the API too much. As far as I remember, there is a queries/s limitations with PyWikiBot ?

Regards

**Comment by fnielsen** [comment]
The data is fetch via the Wikidata Query Service at https://query.wikidata.org/. Some of the panels are direct embeddings, others are processed through Javascript.

**Comment by fnielsen** [comment]
Currently, there is a few elements that is fetched via the MediaWiki API, but most is via Wikidata Query Service.
