### ISSUE TITLE
RSS feeds are empty or only show a few old entries

### ISSUE THREAD

**Issue by gyaoffice** [fnielsen/scholia#822]
RSS feeds for organizations seem to not work properly. E.g. the Technical University of Denmark's feed only shows two old entries, even though they have much more:
https://tools.wmflabs.org/scholia/organization/Q1269766/latest-works/rss
This feed shows none entries at all:
https://tools.wmflabs.org/scholia/organization/Q5570796/latest-works/rss

Maybe I am missing something?

**Comment by egonw** [comment]
No, you're not missing anything. It seems the SPARQL for the feed diverged from that shown. The RSS feed content should be the same for what is shown in the table. Thanks for letting me know!

**Comment by egonw** [comment]
I'm working on updating the SPARQL queries and bring them back in sync.

**Comment by gyaoffice** [comment]
Apologies, but the issue seems to be present still, even though it was closed?

**Comment by egonw** [comment]
@fnielsen, did you deploy the new code since the patch was incorporated? (@gyaoffice, that could explain it...)
