### ISSUE TITLE
Chemical shown in aspect-chooser 

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#824]
@egonw I do not understand why we have this line:

`{ [] wdt:P279 | wdt:P31 wd:{{ q }} . BIND("chemical" AS ?aspect) }`

https://github.com/fnielsen/scholia/blame/master/scholia/app/templates/base.html#L139

**Comment by egonw** [comment]
I am not sure what I was thinking at the time :( This should be removed. I think the idea was that if something is an instance of or subclass of a chemical compound it should be that aspect too, but certainly not what this bit is doing. Sorry about the inconvenience.
