### ISSUE TITLE
Prepare the repo for Hacktoberfest contributions

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#838]
as per 
https://hacktoberfest.digitalocean.com/

**Comment by Daniel-Mietchen** [comment]
We now have a set of issues listed under
https://github.com/fnielsen/scholia/labels/hacktoberfest .

I also brushed the README and CONTRIBUTING files a bit.

Some more preparation could be useful, but I think we're good to go now and can take things up as they develop.

**Comment by egonw** [comment]
Just click the "hacktoberfest" label to get issues suitable (set up by Daniel), which will give this page: https://github.com/fnielsen/scholia/labels/hacktoberfest
