### ISSUE TITLE
Display ORCID iDs

### ISSUE THREAD

**Issue by pigsonthewing** [fnielsen/scholia#85]
In the "Prolific authors" section, please display the subject's ORCID iD (P496), if available.

If not available, please include a "search ORCID" link, formatted like `https://orcid.org/orcid-search/quick-search?searchQuery=Andy+Mabbett`, so that volunteers can more easily find the iDs and add them to Wikidata

**Comment by fnielsen** [comment]
It is now in production, see, e.g., https://tools.wmflabs.org/scholia/venue/Q1981225#Prolific%20authors

**Comment by pigsonthewing** [comment]
Thank you. Any chance the iDs could be made into links, please?

**Comment by fnielsen** [comment]
Whereto? The ORCID website?

**Comment by pigsonthewing** [comment]
Yes; format is http://orcid.org/0000-0001-5882-6823

**Comment by fnielsen** [comment]
It is not immediately possible from the SPARQL endpoint AFAIK, but I am working on some Javascript to convert the WDQS returned data to a more appropriate formed data

**Comment by pigsonthewing** [comment]
This may be relevant: https://www.wikidata.org/wiki/Wikidata:Contact_the_development_team/Archive/2016/12#Linking_external_IDs_in_query_results

**Comment by fnielsen** [comment]
There is now an ORCID link, but I have not yet implement your "Search ORCID" suggestion.

Example: https://tools.wmflabs.org/scholia/venue/Q1981225#Prolific%20authors

**Comment by fnielsen** [comment]
Links for one table was implemented with ceffa39791d1335cb99c53559bf6bb57215ca26e

**Comment by egonw** [comment]
Can this one be closed?

**Comment by fnielsen** [comment]
I suppose there are other aspects where @pigsonthewing would like to have a search link?

**Comment by egonw** [comment]
@fnielsen, then new issues can be opened for this?
