### ISSUE TITLE
Graph is wobbling

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#89]
Graphs, e.g., co-author graphs may be wobbling and never settles.

**Comment by fnielsen** [comment]
The issue is higher up: https://phabricator.wikimedia.org/T163746

**Comment by fnielsen** [comment]
It was already issued here: https://phabricator.wikimedia.org/T146513

**Comment by Kobkaew** [comment]
+1 and the notation is not clear. For instance, the red elliptic means a woman, and what's the white elliptic?

**Comment by fnielsen** [comment]
White means gender unknown (i.e., not set)

**Comment by fnielsen** [comment]
The issue has now been resolved and deployed by https://phabricator.wikimedia.org/T146513
