### ISSUE TITLE
"Missing top authors?"

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#90]
The author profile page has a "Missing co-authors?" under the (wobbly) co-author graph. How about beneath the "top author" graph on the Venue page to have a link for "Missing co-authors?" using the following SPARQL?

    select ?authorname (count(?work) as ?count) where {
      ?work wdt:P1433 wd:Q6294930 .
      ?work wdt:P2093 ?authorname .
    } group by ?authorname
      order by desc(?count)

**Comment by fnielsen** [comment]
Related to #211

**Comment by fnielsen** [comment]
It is running now: https://tools.wmflabs.org/scholia/venue/Q6294930/missing

**Comment by fnielsen** [comment]
There is still the issue when using Magnus Manske's tool that "short author name" is not deleted.

**Comment by Daniel-Mietchen** [comment]
This has been running fine since we switched to the new Author Disambiguator about a year ago.
