### ISSUE TITLE
add Bioschemas annotation to Scholia pages

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#923]
Making them more findable.

**Comment by Daniel-Mietchen** [comment]
Some background in https://bioschemas.gitbook.io/training-portal/tutorials-1/what-and-why-bioschemas.org . No idea how many field-specific schemas there are and which ones are useful.

**Comment by egonw** [comment]
Useful schemas profiles: Event, Taxon, Tool, DataSet, Gene, Journal, MolecularEntity, Organisation, Protein, ScholarlyArticle.

**Comment by egonw** [comment]
A draft design: https://github.com/fnielsen/scholia/pull/1124

**Comment by egonw** [comment]
Gene, MolecularEntity, and Protein are now done: https://github.com/fnielsen/scholia/pull/1125

**Comment by egonw** [comment]
A regression? https://github.com/fnielsen/scholia/issues/1182

**Comment by egonw** [comment]
Okay, in a discussion with @ammar257ammar we found the reason why Google's test tools do not recognize the Bioschemas annotation on this website: it is blocked by Wikidata :(

![image](https://user-images.githubusercontent.com/26721/92116402-12b6e280-edf4-11ea-87fb-42a15eb58c44.png)

cc @AlasdairGray

**Comment by egonw** [comment]
the link behind the blue `robots.txt` in the above screenshot points to https://query.wikidata.org/robots.txt

**Comment by egonw** [comment]
In the BioHackathon last week, information from Scholia was successfully extracted with BMUSE. Reporting pending.

**Comment by egonw** [comment]
Since the `robots.txt` issue, at this moment I will no longer aim at schema.org annotation too. If we want that for some aspects, we can easily add it. In that case, please open one issue for one combination of a Scholia page and a schema.org type.
