### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#959]
Perhaps using our logo as a starting point: https://commons.wikimedia.org/wiki/File:Scholia_logo.svg .

**Comment by fnielsen** [comment]
Are we able to do that? We do not have the top level of tools.wmflabs.org?

**Comment by Daniel-Mietchen** [comment]
Judging on the basis of things like https://tools.wmflabs.org/reasonator/ , there should be a way.

**Comment by carlinmack** [comment]
I think I can get this done wednesday morning, I'm quite familiar with favicons

**Comment by carlinmack** [comment]
Is there a urls.py file for in scholia? or how are pages served, I want to create a redirect for /favicon.ico to the static path

**Comment by fnielsen** [comment]
I am wondering whether HTML base tag could/should be used (too)

**Comment by Daniel-Mietchen** [comment]
Users are beginning to notice: https://twitter.com/GerardMeijssen/status/1202466066175266816

**Comment by fnielsen** [comment]
The favicon is now running.

I had difficulty reviewing the code as I am not familiar with favicon. I thought it was just a question of putting something in the root directory, but I see it is somewhat more elaborate.

**Comment by carlinmack** [comment]
[Need to add a few more redirects](https://realfavicongenerator.net/favicon_checker?protocol=https&site=tools.wmflabs.org%2Fscholia%2F#.Xeh5DxCYWNE) but for 99% of real use cases it's fine :)

**Comment by carlinmack** [comment]
Actually reading what that says, I don't know if we can fully resolve as we aren't serving our site from the / root domain. Therefore I don't think there is much that can be done but that's not a bad thing :)

**Comment by Daniel-Mietchen** [comment]
Looks good enough for the moment. Close?

**Comment by carlinmack** [comment]
👍
