### ISSUE TITLE
Search on the main page is broken

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#963]
neither search nor autosuggestions seem to work.

Pinging @carlinmack

**Comment by fnielsen** [comment]
Have you cleared your cached?

**Comment by Daniel-Mietchen** [comment]
Works again for me, without cleaning the cache. Not sure what that was, but it may have been related to some downtime (ca. 30 min?) earlier.

**Comment by fnielsen** [comment]
Search doesn't seem to work if there is no English description.

**Comment by carlinmack** [comment]
Can you give an example?

**Comment by fnielsen** [comment]
It is in my Javascript function code and was going to fix it. "Carl Edward Rasmussen" is an example.
