### ISSUE TITLE
Revise Scholia paper for Scientometrics 2017

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/scholia#98]
Revise Scholia paper for Scientometrics 2017

- [x] Fix biograph error
- [x] Fix Figure 1. (reviewer 2)
- [x] Upload Figures to commons
- [x] Add \url were missing
- [x] Grammar? "The  plot  is  heavily  biased,  as  only  a  very  limited  subset  of  papers
from the section are available" -> "...is available"
- [x] Introduction: Describe what the paper is about (reviewer 2) Finn added "In the following sections, we describe how Wikidata has been used for bibliographic information and presents Scholia, a website we have built to expose such information. We furthermore show how Scholia can be used for bibliographies and discuss limitation and advantages with Wikidata and Scholia."
- [x] "Why are certain relations surrounded by "" and not others (reviewer 2). Finn erased these quotation marks.
- [x] Why SPARQL instead of API? (reviewer 3) "The label for the item is fetched via Wikidata's MediaWiki API. While some other information can be fetched via this interface, Scholia's many aggregatation queries are better handled with SPARQL."
- [x] User defined queries (reviewer 2). Finn added:  "The embedded WDQS results link back to WDQS where a user can modify the query. The interactive editor of WDQS allows users not familiar with SPARQL to make simple modifications without directly editing the SPARQL code."
- [x] "A motivation of why the currently implemented aspects are aspects..." (reviewer 2). Finn added "The present selection was motivated the possibilities inherent with the Wikidata items and properties.
We plan to extensions with, e.g., year and award."
- [x] Scalability problem: is that a limitation due to SPARQL? (reviewer 3) "The problem is not a limitation of SPARQL, but a limitation set by the server resources."
- [ ] Any information that can be "shown directly by URI de-referencing instead of data downloading"? (reviewer 3) Finn has read this several times and it not sure what it means. 
- [x] catagory (reviewer 3)

**Comment by Daniel-Mietchen** [comment]
re figure upload, I have set up https://commons.wikimedia.org/wiki/Category:Scholia

**Comment by fnielsen** [comment]
I have moved the license information to a footnote

**Comment by fnielsen** [comment]
Figure 1 has been greyisher.

**Comment by fnielsen** [comment]
All figures are now at https://commons.wikimedia.org/wiki/Category:Scholia and the manuscript submitted to EasyChair and the version updated on arXiv.
