### ISSUE TITLE
Regression in the WDQS affecting one of our queries

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#994]
Needs to be reported in Phabricator. It is [this query](https://query.wikidata.org/#SELECT%20%3Fdate%20%3Fwork%20%3FworkLabel%20%3Ftype%20%3Ftopics%0AWITH%20%7B%0A%20%20SELECT%20DISTINCT%20%3Fwork%20WHERE%20%7B%0A%20%20%20%20%7BINCLUDE%20%25RESULTS%0A%20%20BIND%28IRI%28REPLACE%28%3Fformatterurl%2C%20%27%5C%5C%5C%5C%241%27%2C%20str%28%3Fid%29%29%29%20AS%20%3FidUrls%29.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20%20%20%20%20%3Fwork%20wdt%3AP921%20%2F%20%28wdt%3AP527%2B%20%7C%20wdt%3AP1269%2B%20%7C%20%28wdt%3AP31%2a%20%2F%20wdt%3AP279%2a%29%20%29%20wd%3AQ289372%20.%0A%20%20%20%20%7D%20UNION%20%7B%0A%20%20%20%20%20%20wd%3AQ289372%20%3Fpropp%20%3Fstatement%20.%0A%20%20%20%20%20%20%3Fstatement%20a%20wikibase%3ABestRank%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20prov%3AwasDerivedFrom%2Fpr%3AP248%20%3Fwork%20.%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%20AS%20%25works%0AWITH%20%7B%0A%20%20SELECT%20%28MAX%28%3Fdates%29%20as%20%3Fdatetime%29%20%3Fwork%20%28GROUP_CONCAT%28DISTINCT%20%3Ftype_label%3B%20separator%3D%22%2C%20%22%29%20AS%20%3Ftype%29%20%28GROUP_CONCAT%28DISTINCT%20%3Ftopic_label%3B%20separator%3D%22%20%2F%2F%20%22%29%20AS%20%3Ftopics%29%20WHERE%20%7B%0A%20%20%20%20INCLUDE%20%25works%0A%20%20%20%20%3Fwork%20wdt%3AP921%20%3Ftopic%20.%20%0A%20%20%20%20OPTIONAL%20%7B%20%3Fwork%20wdt%3AP31%20%3Ftype_%20.%20%3Ftype_%20rdfs%3Alabel%20%3Ftype_label%20.%20FILTER%20%28LANG%28%3Ftype_label%29%20%3D%20%27en%27%29%20%7D%0A%20%20%20%20OPTIONAL%20%7B%20%3Fwork%20wdt%3AP577%20%3Fdates%20.%20%7D%0A%20%20%20%20%3Ftopic%20rdfs%3Alabel%20%3Ftopic_label%20.%20%20FILTER%20%28lang%28%3Ftopic_label%29%20%3D%20%27en%27%29%0A%20%20%7D%0A%20%20GROUP%20BY%20%3Fwork%0A%7D%20AS%20%25result%0AWHERE%20%7B%0A%20%20INCLUDE%20%25result%0A%20%20BIND%28xsd%3Adate%28%3Fdatetime%29%20AS%20%3Fdate%29%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cda%2Cde%2Ces%2Cfr%2Cjp%2Cnl%2Cno%2Cru%2Csv%2Czh%22.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fdate%29%0ALIMIT%20500%0A) (from the `/chemical/` aspect). This is a recent regression.

**Comment by fnielsen** [comment]
The commit to fix this issue should be running now: https://tools.wmflabs.org/scholia/chemical/Q2270
